feat(cdn): add item gc
ovh/cds pull request #5397
Opened 2020-08-26 10:22 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-08-26 10:40 UTC, ovh-cds commented
CDS Report build-all-cds#14234.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-08-26 12:39 UTC, yesnault approved these changes

2020-08-26 12:45 UTC, fsamin requested changes

2020-08-26 12:45 UTC, fsamin commented on engine/cdn/cdn_item.go
> +	item.Hash = hex.EncodeToString(h.Sum(nil))
with the symmecrypt update, convergent.NewHash returns a string, so you don't need to do `hex.EncodeToString(h.Sum(nil))`

2020-08-26 12:45 UTC, fsamin commented on engine/cdn/index/dao.go
> +            last_modified < NOW() - $2 * INTERVAL '1 second'
order by ?

2020-08-26 12:45 UTC, fsamin commented on engine/cdn/index/dao.go
> +func LoadOldItemIDsByStatusAndDuration(db gorp.SqlExecutor, status string, duration int) ([]string, error) {
add options if you need decryption

2020-08-26 16:56 UTC, richardlt approved these changes

2020-08-28 08:42 UTC, ovh-cds commented
CDS Report build-all-cds#14261.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-08-31 08:27 UTC, ovh-cds commented
CDS Report build-all-cds#14261.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-08-31 09:04 UTC, ovh-cds commented
CDS Report build-all-cds#14269.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-08-31 10:02 UTC, yesnault approved these changes

2020-08-31 10:05 UTC, merged