feat(api,ui): help text
ovh/cds pull request #5398
Opened 2020-08-26 13:40 UTC by yesnault

close #5178

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2020-08-26 13:47 UTC, sguiheux requested changes

2020-08-26 13:47 UTC, sguiheux commented on ui/src/app/views/navbar/navbar.html
> +        <button *ngIf="help && help.content && help.content.length > 0"
help?.content?.length > 0   (something like that)

2020-08-26 13:47 UTC, sguiheux commented on ui/src/app/shared/toast/toast-http-error.html
> +    <div *ngIf="toast.data.help && toast.data.help.length > 0">
toast?.data?.help?.length > 0 .   something like that

2020-08-26 14:10 UTC, ovh-cds commented
CDS Report build-all-cds#14243.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

2020-08-26 17:01 UTC, richardlt commented on ui/src/assets/i18n/en.json
> +  "toast_http_error_request_id": "with this request ID:",
I think we can let the old traduction for the case there is no message in the api config.

2020-08-27 09:44 UTC, fsamin requested changes

2020-08-27 09:44 UTC, fsamin commented on engine/api/api_routes.go
> +	r.Handle("/help", ScopeNone(), r.GET(api.getHelpHandler, Auth(false)))
```suggestion
	r.Handle("/help", ScopeNone(), r.GET(api.getHelpHandler))
```

2020-08-27 09:44 UTC, fsamin commented on engine/api/api_routes.go
> +	r.Handle("/help", ScopeNone(), r.GET(api.getHelpHandler, Auth(false)))
i would keep authentication, if the help message contains contact information, we may only want to give them to registered users

2020-08-27 09:44 UTC, fsamin commented on ui/src/assets/i18n/fr.json
> +  "toast_http_error_request_id": "avec cet identifiant de requête:",
i prefer the old message

2020-08-27 12:03 UTC, sguiheux approved these changes

2020-08-27 12:45 UTC, ovh-cds commented
CDS Report build-all-cds#14251.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-08-27 14:42 UTC, ovh-cds commented
CDS Report build-all-cds#14254.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-08-27 15:33 UTC, richardlt approved these changes

2020-08-27 15:42 UTC, fsamin approved these changes

2020-08-28 07:16 UTC, merged