doc: add cdn doc + migration to cdn
ovh/cds pull request #5425
Opened 2020-09-18 15:43 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-09-18 15:53 UTC, ovh-cds commented
CDS Report build-all-cds#14403.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✘  
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-09-21 08:46 UTC, yesnault requested changes

2020-09-21 08:46 UTC, yesnault commented on docs/content/docs/components/cdn/_index.md
> +CDN is a service dedicated to receice and retrieve logs. It replaces the old system that stored logs in the CDS database
```suggestion
CDN is a service dedicated to receive and retrieve logs. 
```

2020-09-21 08:46 UTC, yesnault commented on docs/content/docs/components/cdn/_index.md
> +* Buffer Unit: to store step log temporarily during the execution
```suggestion
* Buffer Unit: to store step log temporarily during the execution of a job
```

2020-09-21 10:40 UTC, ovh-cds commented
CDS Report build-all-cds#14408.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-09-21 13:49 UTC, yesnault approved these changes

2020-09-22 20:28 UTC, richardlt approved these changes

2020-09-23 06:39 UTC, merged