fix: allow to skip project sync
ovh/cds pull request #5426
Opened 2020-09-21 10:08 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-09-21 13:47 UTC, yesnault requested changes

2020-09-21 13:47 UTC, yesnault commented on engine/cdn/cdn_sync.go
> +	if len(listNodeRuns) == len(nodeRunIds) {
this check should be skipped

2020-09-21 19:20 UTC, yesnault requested changes

2020-09-21 19:20 UTC, yesnault commented on engine/cdn/cdn_sync.go
> +	// Test if all noderun has been sync for this project
```suggestion
	// Test if all noderuns have been sync for this project
```

2020-09-22 07:57 UTC, yesnault approved these changes

2020-09-22 20:31 UTC, richardlt approved these changes

2020-09-23 07:35 UTC, yesnault approved these changes

2020-09-23 07:36 UTC, fsamin approved these changes

2020-09-23 08:15 UTC, merged