feat: status for all instances
ovh/cds pull request #5437
Opened 2020-09-24 16:57 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2020-09-24 17:15 UTC, richardlt approved these changes

2020-09-24 17:27 UTC, ovh-cds commented
CDS Report build-all-cds#14450.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-09-25 07:21 UTC, sguiheux approved these changes

2020-09-25 07:22 UTC, fsamin requested changes

2020-09-25 07:22 UTC, fsamin commented on cli/cdsctl/admin_cdn.go
> +	services, err := client.ServicesByType("cdn")
use constant

2020-09-25 07:22 UTC, fsamin commented on engine/api/services/dao.go
> +	return withServiceStatus(ctx, db, services)
it could be nice to pass a loader optional function as we are doing in other packages

2020-09-25 08:52 UTC, fsamin requested changes

2020-09-25 08:52 UTC, fsamin commented on engine/api/services/dao.go
> +func loadAllServiceStatusByServiceID(ctx context.Context, db gorp.SqlExecutor, serviceID int64) ([]sdk.ServiceStatus, error) {
deadcode

2020-09-25 09:29 UTC, ovh-cds commented
CDS Report build-all-cds#14461.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-09-25 11:32 UTC, richardlt approved these changes

2020-09-25 12:04 UTC, ovh-cds commented
CDS Report build-all-cds#14468.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-09-25 14:02 UTC, fsamin approved these changes

2020-09-25 14:25 UTC, merged