feat(cdn): auth from cds api jwt
ovh/cds pull request #5444
Opened 2020-09-25 16:15 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-09-25 16:27 UTC, ovh-cds commented
CDS Report build-all-cds#14477.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✘  
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-09-28 10:02 UTC, ovh-cds commented
CDS Report build-all-cds#14487.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-09-28 18:40 UTC, ovh-cds commented
CDS Report build-all-cds#14508.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-09-29 07:06 UTC, yesnault approved these changes

2020-09-29 07:53 UTC, ovh-cds commented
CDS Report build-all-cds#14510.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone tests 1 -   
  * Standalone tests 2 -   
  * Standalone tests 3 -

2020-09-30 07:09 UTC, fsamin requested changes

2020-09-30 07:09 UTC, fsamin commented on engine/cdn/auth.go
> +	vars := mux.Vars(req)
add telemetry.Span

2020-09-30 07:09 UTC, fsamin commented on engine/cdn/auth.go
> +	// Check for session based on jwt from context
add telemetry.Span

2020-09-30 07:09 UTC, fsamin commented on engine/cdn/auth.go
> +	if err := s.Client.WorkflowLogAccess(item.APIRef.ProjectKey, item.APIRef.WorkflowName, sessionID); err != nil {
i could be nice to ba able to give this func a ctx to be able to track the telemetry.span through cdn + api

2020-09-30 07:09 UTC, fsamin commented on engine/cdn/item_logs_handler.go
> +		refreshDelay, err := strconv.ParseInt(r.FormValue("refresh"), 10, 64)
you can use `FormInt`

2020-09-30 07:40 UTC, sguiheux approved these changes

2020-09-30 10:39 UTC, ovh-cds commented
CDS Report build-all-cds#14533.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-09-30 14:11 UTC, fsamin approved these changes

2020-09-30 14:11 UTC, merged