fix(engine): manage signout
ovh/cds pull request #5467
Opened 2020-10-01 09:01 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2020-10-01 11:57 UTC, fsamin requested changes

2020-10-01 11:57 UTC, fsamin commented on engine/cmd_start.go
> +			stopping(ctx, serviceConfs)
```suggestion
			unregisterServices(ctx, serviceConfs)
```

2020-10-01 11:57 UTC, fsamin commented on engine/cmd_start.go
> +func stopping(ctx context.Context, serviceConfs []serviceConf) {
```suggestion
func unregisterServices(ctx context.Context, serviceConfs []serviceConf) {
```

2020-10-01 17:47 UTC, richardlt approved these changes

2020-10-02 07:33 UTC, fsamin approved these changes

2020-10-02 08:08 UTC, sguiheux approved these changes

2020-10-02 08:08 UTC, merged