feat(cdn): purge and deduplication
ovh/cds pull request #5516
Opened 2020-10-20 09:43 UTC by fsamin

2020-10-20 09:54 UTC, sguiheux requested changes

2020-10-20 09:54 UTC, sguiheux commented on engine/cdn/storage/storageunit.go
> +		tickrPurge := time.NewTicker(time.Second)
missing defer Stop

2020-10-20 11:43 UTC, fsamin commented on engine/cdn/storage/storageunit.go
> +		tickrPurge := time.NewTicker(time.Second)
done

2020-10-20 11:44 UTC, sguiheux approved these changes

2020-10-20 11:53 UTC, ovh-cds commented
CDS Report build-all-cds#14775.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-21 09:29 UTC, richardlt requested changes

2020-10-21 09:29 UTC, richardlt commented on engine/api/api_routes.go
> +	r.Handle("/auth/session/{sessionID}", ScopeNone(), r.GET(api.getAuthSession))
Only admin should be able to call this route.

2020-10-22 13:26 UTC, yesnault approved these changes

2020-10-22 13:28 UTC, richardlt approved these changes

2020-10-22 13:46 UTC, ovh-cds commented
CDS Report build-all-cds#14795.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-22 14:59 UTC, ovh-cds commented
CDS Report build-all-cds#14797.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-22 19:44 UTC, merged