feat(ui,cdn): display logs from cdn using stream
ovh/cds pull request #5518
Opened 2020-10-20 16:58 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-10-20 17:11 UTC, ovh-cds commented
CDS Report build-all-cds#14778.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-20 17:40 UTC, ovh-cds commented
CDS Report build-all-cds#14779.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-20 22:09 UTC, ovh-cds commented
CDS Report build-all-cds#14782.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ■

2020-10-20 22:09 UTC, ovh-cds commented
CDS Report build-all-cds#14782.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ■

2020-10-20 22:37 UTC, ovh-cds commented
CDS Report build-all-cds#14783.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-20 23:00 UTC, ovh-cds commented
CDS Report build-all-cds#14783.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-10-20 23:31 UTC, ovh-cds commented
CDS Report build-all-cds#14785.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-21 09:42 UTC, sguiheux approved these changes

2020-10-21 09:42 UTC, sguiheux approved these changes

2020-10-21 10:01 UTC, ovh-cds commented
CDS Report build-all-cds#14788.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-21 12:13 UTC, ovh-cds commented
CDS Report build-all-cds#14789.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ✔ 
  * Test UI ■

2020-10-21 12:13 UTC, ovh-cds commented
CDS Report build-all-cds#14789.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ■   
  * Test SDK Rust ✔ 
  * Test UI ■

2020-10-21 19:19 UTC, fsamin requested changes

2020-10-21 19:19 UTC, fsamin commented on engine/cdn/cdn_log_dequeue.go
> +	go s.publishWSEvent(*it)
protect this with sdk.GoRoutine.Exec

2020-10-22 11:04 UTC, richardlt commented on engine/cdn/cdn_log_dequeue.go
> +	go s.publishWSEvent(*it)
done

2020-10-22 11:22 UTC, ovh-cds commented
CDS Report build-all-cds#14792.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-10-22 11:30 UTC, yesnault approved these changes

2020-10-22 12:36 UTC, ovh-cds commented
CDS Report build-all-cds#14794.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-10-22 15:03 UTC, fsamin approved these changes

2020-10-22 15:03 UTC, merged