feat(cdn): init cds backend config
ovh/cds pull request #5533
Opened 2020-11-04 16:44 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-11-04 17:05 UTC, fsamin approved these changes

2020-11-04 17:28 UTC, ovh-cds commented
CDS Report build-all-cds#14842.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✘  
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-04 18:26 UTC, ovh-cds commented
CDS Report build-all-cds#14842.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✘  
  * Sonar ✔

2020-11-05 09:21 UTC, sguiheux requested changes

2020-11-05 09:21 UTC, sguiheux commented on engine/cdn/storage/cds/cds.go
> +func (c *CDS) Write(_ sdk.CDNItemUnit, r io.Reader, w io.Writer) error {
maybe return nil ?  no write impementation on CDS backend

2020-11-05 10:27 UTC, yesnault approved these changes

2020-11-06 14:48 UTC, richardlt commented on engine/cdn/storage/cds/cds.go
> +func (c *CDS) Write(_ sdk.CDNItemUnit, r io.Reader, w io.Writer) error {
done

2020-11-06 15:49 UTC, yesnault approved these changes

2020-11-09 09:18 UTC, sguiheux approved these changes

2020-11-09 09:44 UTC, ovh-cds commented
CDS Report build-all-cds#14885.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-09 10:51 UTC, merged