fix(cdn): add rate limit + check buffer size before adding line
ovh/cds pull request #5536
Opened 2020-11-05 09:09 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-11-05 09:09 UTC, ovh-cds commented
CDS Report build-all-cds#14845.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 10:02 UTC, ovh-cds commented
CDS Report build-all-cds#14846.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 10:23 UTC, richardlt commented on engine/cdn/storage/redis/redis.go
> +				redis.call('zadd', KEYS[1], tonumber(KEYS[3]), "\"" .. tonumber(KEYS[3])+1 .. "#...truncated\"");
```suggestion
				redis.call('zadd', KEYS[1], tonumber(KEYS[3]), "\"" .. tonumber(KEYS[3])+1 .. "#...truncated\n\"");
```

2020-11-05 10:37 UTC, yesnault approved these changes

2020-11-05 10:55 UTC, richardlt approved these changes

2020-11-05 11:09 UTC, ovh-cds commented
CDS Report build-all-cds#14850.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 11:35 UTC, ovh-cds commented
CDS Report build-all-cds#14853.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 11:35 UTC, ovh-cds commented
CDS Report build-all-cds#14852.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 14:06 UTC, ovh-cds commented
CDS Report build-all-cds#14854.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-05 16:23 UTC, yesnault approved these changes

2020-11-05 21:02 UTC, ovh-cds commented
CDS Report build-all-cds#14854.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-06 08:35 UTC, fsamin requested changes

2020-11-06 08:35 UTC, fsamin commented on engine/cdn/storage/redis/redis.go
> +	maxStepLogSize = maxStepLog
i think maxStepLogSize should be attribute of Redis and not at package level

2020-11-06 08:52 UTC, ovh-cds commented
CDS Report build-all-cds#14854.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-06 09:29 UTC, ovh-cds commented
CDS Report build-all-cds#14859.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-06 10:47 UTC, ovh-cds commented
CDS Report build-all-cds#14860.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-06 11:42 UTC, ovh-cds commented
CDS Report build-all-cds#14866.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-09 07:45 UTC, fsamin requested changes

2020-11-09 07:45 UTC, fsamin commented on engine/cache/redis.go
> +	log.Info(context.TODO(), "Eval: %s  %v", expr, args)
log.Debug or remove the log

2020-11-09 09:00 UTC, fsamin approved these changes

2020-11-09 09:01 UTC, merged