feat(cdsctl): allow manual run a pipeline not launched
ovh/cds pull request #5552
Opened 2020-11-17 09:49 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-11-17 09:52 UTC, richardlt commented on cli/cdsctl/workflow_run.go
>  			}
Can we break this loop ?

2020-11-17 10:02 UTC, fsamin requested changes

2020-11-17 10:02 UTC, fsamin commented on cli/cdsctl/workflow_run.go
> +				fromNodeID = node.ID
be careful, fromNodeId is not a pointer and you are scoped in a closure

2020-11-17 10:04 UTC, sguiheux approved these changes

2020-11-17 10:16 UTC, ovh-cds commented
CDS Report build-all-cds#14909.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-17 11:06 UTC, yesnault commented on cli/cdsctl/workflow_run.go
>  			}
fixed

2020-11-17 11:26 UTC, ovh-cds commented
CDS Report build-all-cds#14911.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-18 09:24 UTC, fsamin approved these changes

2020-11-20 09:18 UTC, richardlt approved these changes

2020-11-20 10:05 UTC, ovh-cds commented
CDS Report build-all-cds#14928.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2020-11-20 11:01 UTC, merged