fix(cdn): manage worker without private key in cache
ovh/cds pull request #5566
Opened 2020-11-26 15:12 UTC by sguiheux

If service log arrive before worker registering, worker in cdn cache doesn't have a private key

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-11-26 15:13 UTC, yesnault approved these changes

2020-11-26 15:31 UTC, ovh-cds commented
CDS Report build-all-cds#14963.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-11-26 16:26 UTC, ovh-cds commented
CDS Report build-all-cds#14963.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-27 09:06 UTC, fsamin requested changes

2020-11-27 09:06 UTC, fsamin commented on engine/cdn/cdn_log_tcp.go
>  	}
```suggestion
	if ok {
	    w, ok := cacheData.(sdk.Worker)
	    if ok && (!opts.NeedPrivateKey || len(w.PrivateKey) > 0) {
		      return w, nil
		  }
	}
```

2020-11-27 09:40 UTC, ovh-cds commented
CDS Report build-all-cds#14970.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-27 10:31 UTC, ovh-cds commented
CDS Report build-all-cds#14972.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-27 11:16 UTC, ovh-cds commented
CDS Report build-all-cds#14972.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2020-11-27 14:20 UTC, richardlt approved these changes

2020-11-27 14:43 UTC, fsamin approved these changes

2020-11-27 14:43 UTC, merged