feat: detach fromRepository with force import
ovh/cds pull request #5578
Opened 2020-12-03 23:14 UTC by yesnault

2020-12-03 23:45 UTC, ovh-cds commented
CDS Report build-all-cds#15035.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2020-12-04 10:00 UTC, ovh-cds commented
CDS Report build-all-cds#15036.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-12-04 10:34 UTC, ovh-cds commented
CDS Report build-all-cds#15037.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-12-04 11:00 UTC, ovh-cds commented
CDS Report build-all-cds#15037.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-12-04 13:07 UTC, ovh-cds commented
CDS Report build-all-cds#15039.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-12-04 13:26 UTC, richardlt approved these changes

2020-12-04 13:27 UTC, fsamin approved these changes

2020-12-04 13:34 UTC, sguiheux requested changes

2020-12-04 13:34 UTC, sguiheux commented on engine/api/ascode/dao.go
> +func DeleteEventsApplicationOnlyFromPipelineName(ctx context.Context, db gorp.SqlExecutor, fromRepository string, appID int64, appName string) error {
PipelineName ?

2020-12-04 13:34 UTC, sguiheux commented on engine/api/ascode/dao.go
> +func DeleteEventsEnvironmentOnlyFromPipelineName(ctx context.Context, db gorp.SqlExecutor, fromRepository string, envID int64, envName string) error {
EnvironmentName

2020-12-04 13:35 UTC, sguiheux approved these changes

2020-12-04 13:51 UTC, ovh-cds commented
CDS Report build-all-cds#15043.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2020-12-04 14:19 UTC, merged