fix(hatchery:vsphere): update vmware deps + fix auth secrets
ovh/cds pull request #5599
Opened 2020-12-17 10:24 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2020-12-17 16:23 UTC, fsamin requested changes

2020-12-17 16:23 UTC, fsamin commented on engine/hatchery/vsphere/spawn.go
> +		}
```suggestion
                var err error
		vm, err = h.createVMModel(*spawnArgs.Model, spawnArgs.WorkerName)
		if err != nil {
			log.Error(ctx, "Unable to create VM Model: %v", err)
			return err
		}
```

2020-12-17 16:23 UTC, fsamin commented on engine/hatchery/vsphere/spawn.go
>  	if vm == nil || errV != nil {
is the test on errBV still useful ?

2020-12-17 16:23 UTC, fsamin commented on engine/hatchery/vsphere/spawn.go
> +	cloneSpec, folder, errCfg := h.createVMConfig(vm, annot, spawnArgs.WorkerName)
s/errCfg/err

2020-12-17 16:23 UTC, fsamin commented on engine/hatchery/vsphere/spawn.go
> +	ip, errW := vmWorker.WaitForIP(ctx, true)
s/errW/err

2020-12-17 16:23 UTC, fsamin commented on engine/hatchery/vsphere/vsphere.go
> +			return fmt.Errorf("flag or environment variable openstack-ip-range error: %s", err)
```suggestion
			return fmt.Errorf("flag or environment variable openstack-ip-range error: %v", err)
```

2020-12-17 16:23 UTC, fsamin commented on sdk/hatchery/model.go
> +			return sdk.WrapError(err, "cannot interpolate registry password for model %s", model.Path())
is it still a registry password ?

2020-12-18 09:09 UTC, ovh-cds commented
CDS Report build-all-cds#15095.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2020-12-18 09:09 UTC, ovh-cds commented
CDS Report build-all-cds#15095.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2020-12-18 09:24 UTC, yesnault requested changes

2020-12-18 09:24 UTC, yesnault commented on engine/hatchery/vsphere/types.go
> +	IPRange string `mapstructure:"iprange" toml:"iprange" default:"" commented:"false" comment:"Facultative. IP Range for spawned workers. \n Format: a.a.a.a/b,c.c.c.c/e \n Hatchery will use an IP from
```suggestion
	IPRange string `mapstructure:"iprange" toml:"iprange" default:"" commented:"false" comment:"Facultative. IP Range for spawned workers. \n Format: a.a.a.a/b,c.c.c.c/e \n Hatchery will use an IP from this range to create Virtual Machine (Fixed IP Attribute).\nIf not set, you have to set it in your worker model template" json:"iprange,omitempty"`
```

2020-12-18 09:24 UTC, yesnault commented on engine/hatchery/vsphere/types.go
> +	DNS string `mapstructure:"dns" toml:"dns" default:"" commented:"false" comment:"Facultative. DNS IP" json:"dns,omitempty"`
```suggestion
	DNS string `mapstructure:"dns" toml:"dns" default:"" commented:"false" comment:"Optional. DNS IP" json:"dns,omitempty"`
```

2020-12-18 10:59 UTC, sguiheux commented on sdk/hatchery/model.go
> +			return sdk.WrapError(err, "cannot interpolate registry password for model %s", model.Path())
in this case yes

2020-12-18 11:02 UTC, yesnault approved these changes

2020-12-18 11:30 UTC, fsamin approved these changes

2020-12-19 10:45 UTC, ovh-cds commented
CDS Report build-all-cds#15109.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ■

2020-12-19 10:45 UTC, ovh-cds commented
CDS Report build-all-cds#15109.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ■

2020-12-21 08:33 UTC, richardlt approved these changes

2020-12-30 17:06 UTC, ovh-cds commented
CDS Report build-all-cds#15172.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2020-12-30 17:06 UTC, ovh-cds commented
CDS Report build-all-cds#15172.0 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2020-12-31 14:22 UTC, ovh-cds commented
CDS Report build-all-cds#15191.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-01-04 09:31 UTC, merged