feat(cdn): add upload artifact handler
ovh/cds pull request #5637
Opened 2021-01-13 17:07 UTC by sguiheux

- New Buffer that use local FS
- Upload artifact Handler

@ovh/cds

2021-01-14 16:07 UTC, fsamin requested changes

2021-01-14 16:07 UTC, fsamin commented on engine/cdn/cdn_sync.go
>  func (s *Service) SyncBuffer(ctx context.Context) {
probably this function should also be part of RunningStorageUnits

2021-01-14 16:07 UTC, fsamin commented on engine/cdn/item/gorp_model.go
>  func toItemDB(c sdk.CDNItem) *cdnItemDB {
don't return a pointer

2021-01-14 16:07 UTC, fsamin commented on engine/cdn/storage/cds/cds.go
> +		logApiRef, is := i.Item.APIRef.(*sdk.CDNLogAPIRef)
put this statement in a nicer method of `sdk.CDNItem`

2021-01-15 16:49 UTC, yesnault approved these changes

2021-01-18 09:47 UTC, richardlt approved these changes

2021-01-18 09:47 UTC, richardlt commented on engine/cdn/cdn_file.go
> +	}
defer tx rollback

2021-01-18 09:47 UTC, richardlt commented on engine/cdn/item_upload.go
> +			return err
```suggestion
			return sdk.WithStack(err)
```

2021-01-18 09:47 UTC, richardlt commented on engine/cdn/item_upload.go
> +				return err
```suggestion
				return sdk.WithStack(err)
```

2021-01-18 09:47 UTC, richardlt commented on engine/cdn/storage/storageunit.go
> +				return nil, fmt.Errorf("local driver is not available")
```suggestion
				return nil, sdk.WithStack(fmt.Errorf("local driver is not available"))
```

2021-01-18 09:47 UTC, richardlt commented on engine/cdn/storage/storageunit.go
> +				return nil, fmt.Errorf("local driver is not a buffer unit driver")
```suggestion
				return nil, sdk.WithStack(fmt.Errorf("local driver is not a buffer unit driver"))
```

2021-01-18 10:19 UTC, ovh-cds commented
CDS Report build-all-cds#15279.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-01-18 16:19 UTC, fsamin approved these changes

2021-01-19 13:44 UTC, merged