fix(api,ui): wrong error check
ovh/cds pull request #5643
Opened 2021-01-19 16:33 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-01-19 16:34 UTC, yesnault approved these changes

2021-01-19 16:38 UTC, richardlt requested changes
Can you also remove the Selector for user cause if it's not fetch anymore we should also stop to get its value that will be always null ?

2021-01-19 16:51 UTC, ovh-cds commented
CDS Report build-all-cds#15288.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-01-19 19:52 UTC, ovh-cds commented
CDS Report build-all-cds#15289.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

2021-01-20 08:42 UTC, fsamin approved these changes

2021-01-20 09:59 UTC, richardlt approved these changes

2021-01-20 09:59 UTC, merged