feat(cdn): worker upload artifact on CDN
ovh/cds pull request #5646
Opened 2021-01-20 09:54 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-01-20 13:11 UTC, yesnault approved these changes

2021-01-21 08:48 UTC, richardlt approved these changes

2021-01-22 08:36 UTC, fsamin requested changes

2021-01-22 08:36 UTC, fsamin commented on engine/api/workflow_queue.go
> +		featureName := "cdn-artifact"
put this is in a constant

2021-01-22 08:36 UTC, fsamin commented on engine/worker/internal/action/builtin_artifact_upload.go
> +	cdnArtifactEnabled := wk.FeatureEnabled("cdn-artifact")
replace "cdn-artifact" by a constant defined elsewhere

2021-01-22 08:36 UTC, fsamin commented on engine/worker/internal/action/builtin_artifact_upload.go
>  			log.Debug(ctx, "worker.RunArtifactUpload> Uploading %s projectKey:%v integrationName:%v job:%d", path, projectKey, integrationName, jobID)
in fact, now you don't need to write `worker.RunArtifactUpload>` because this is automatically added as field in the logs

2021-01-22 08:36 UTC, fsamin commented on engine/worker/internal/action/builtin_artifact_upload.go
> +				log.Error(ctx, "worker.RunArtifactUpload> unable to sign: %v", err)
```suggestion
				log.Error(ctx, "unable to sign artifact: %v", err)
```

2021-01-22 08:36 UTC, fsamin commented on engine/worker/internal/action/builtin_artifact_upload.go
> +				log.Error(ctx, "worker.RunArtifactUpload> CDNArtifactUpdload failed for %s: %v", path, err)
```suggestion
				log.Error(ctx, "unable to upload artifact %q: %v", path, err)
```

2021-01-22 08:36 UTC, fsamin commented on sdk/cdsclient/client_cdn.go
> +	for i := 0; i < c.config.Retry; i++ {
this retry pattern is already done ins http.Stream function

2021-01-22 08:51 UTC, fsamin approved these changes

2021-01-22 09:08 UTC, ovh-cds commented
CDS Report build-all-cds#15298.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-01-22 10:24 UTC, ovh-cds commented
CDS Report build-all-cds#15298.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2021-01-22 10:24 UTC, ovh-cds commented
CDS Report build-all-cds#15298.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package and Analyze
  * Docker ✔ 
  * Sonar ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2021-01-22 10:24 UTC, merged