fix(api): upload artifact for vcs release
ovh/cds pull request #5717
Opened 2021-02-23 14:03 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-02-23 15:00 UTC, fsamin requested changes

2021-02-23 15:00 UTC, fsamin commented on engine/vcs/github/http.go
> +		req.ContentLength = int64(s)
Add a comment to explain why...

2021-02-23 15:01 UTC, yesnault approved these changes

2021-02-23 15:26 UTC, richardlt approved these changes

2021-02-23 15:36 UTC, sguiheux commented on engine/vcs/github/http.go
> +		req.ContentLength = int64(s)
done

2021-02-24 17:13 UTC, fsamin approved these changes

2021-03-01 10:19 UTC, merged