fix(cdn): clean Incoming item without item unit
ovh/cds pull request #5722
Opened 2021-02-24 11:08 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-02-24 11:36 UTC, fsamin approved these changes

2021-02-24 16:44 UTC, yesnault approved these changes

2021-02-25 10:19 UTC, richardlt approved these changes

2021-02-25 10:20 UTC, richardlt requested changes

2021-02-25 10:20 UTC, richardlt commented on engine/cdn/cdn_gc.go
> +				return err
_ = tx.Rollback()

2021-03-01 10:26 UTC, richardlt approved these changes

2021-03-01 11:12 UTC, ovh-cds commented
CDS Report build-all-cds#15667.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-03-01 13:31 UTC, ovh-cds commented
CDS Report build-all-cds#15667.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-03-02 08:19 UTC, merged