feat(cdn): remove storage unit
ovh/cds pull request #5729
Opened 2021-03-01 10:00 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-03-01 10:20 UTC, richardlt requested changes
I think than rather then checking for unit to delete with a ticker and because dropping a unit is not a usual action. It could be better to have a some commands:
- one to "disable" the unit (off sync, stop loading data from this unit).
- a another to mark all unit_items to delete. 
- a last one to direct delete the item that fails if there are still unit_items.

2021-03-01 10:20 UTC, richardlt commented on engine/sql/cdn/013_storage_unit_to_delete.sql
> +ALTER TABLE  storage_unit DROP COLUMN to_delete;
```suggestion
ALTER TABLE storage_unit DROP COLUMN to_delete;
```

2021-03-01 10:20 UTC, richardlt commented on engine/cdn/storage/dao.go
> +	query := "SELECT id FROM storage_unit_item WHERE unit_id = $1 to_delete = false ORDER BY id ASC OFFSET $2 LIMIT $3"
```suggestion
	query := "SELECT id FROM storage_unit_item WHERE unit_id = $1 AND to_delete = false ORDER BY id ASC OFFSET $2 LIMIT $3"
```

2021-03-01 10:20 UTC, richardlt commented on cli/cdsctl/admin_cdn_unit.go
> +func adminCdnUnit() *cobra.Command {
Could be nice to have a command to list existing unit and get their ids.

2021-03-01 10:20 UTC, richardlt commented on engine/cdn/cdn_gc.go
> +	units, err := storage.LoadAllUnits(ctx, s.Mapper, s.mustDBWithCtx(ctx))
Direct load unit to delete ?

2021-03-01 10:26 UTC, ovh-cds commented
CDS Report build-all-cds#15665.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-03-01 11:40 UTC, ovh-cds commented
CDS Report build-all-cds#15669.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-03-01 14:27 UTC, ovh-cds commented
CDS Report build-all-cds#15674.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-03-02 08:37 UTC, ovh-cds commented
CDS Report build-all-cds#15674.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-03-02 09:09 UTC, fsamin approved these changes

2021-03-02 09:29 UTC, richardlt approved these changes

2021-03-02 09:32 UTC, merged