feat: add builtin action PushBuildInfo
ovh/cds pull request #5824
Opened 2021-05-24 11:59 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-05-24 12:11 UTC, fsamin approved these changes

2021-05-24 12:28 UTC, richardlt submitted a review, later dismissed

2021-05-24 18:40 UTC, yesnault requested changes

2021-05-24 18:40 UTC, yesnault commented on engine/worker/internal/action/builtin_build_info.go
> +		return sdk.Result{}, fmt.Errorf("error deploying application: %v", err)
```suggestion
		return sdk.Result{}, fmt.Errorf("error while running integration plugin: %v", err)
```

2021-05-24 18:40 UTC, yesnault commented on sdk/exportentities/step.go
> +	PushBuildInfo    *StepPushBuildInfo    `json:"pushBuildInfo,omitempty" yaml:"pushBuildInfo,omitempty" jsonschema:"oneof_required=actionPushBuildInfo" jsonschema_description:"Push build info.\nhttps:
md files in another PR?

2021-05-25 09:21 UTC, sguiheux commented on sdk/exportentities/step.go
> +	PushBuildInfo    *StepPushBuildInfo    `json:"pushBuildInfo,omitempty" yaml:"pushBuildInfo,omitempty" jsonschema:"oneof_required=actionPushBuildInfo" jsonschema_description:"Push build info.\nhttps:
doc will come later

2021-05-25 09:39 UTC, ovh-cds commented
CDS Report build-all-cds#16058.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-05-25 10:37 UTC, yesnault approved these changes

2021-05-25 14:45 UTC, ovh-cds commented
CDS Report build-all-cds#16064.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-05-26 08:30 UTC, ovh-cds commented
CDS Report build-all-cds#16064.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-05-27 08:11 UTC, richardlt approved these changes

2021-05-27 08:49 UTC, ovh-cds commented
CDS Report build-all-cds#16064.3 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2021-06-14 14:11 UTC, merged