feat(contrib,engine): add release action + artifactory release plugin
ovh/cds pull request #5834
Opened 2021-06-04 15:15 UTC by sguiheux

Do not merge it. Waiting to merge #5824  first

@ovh/cds

2021-06-04 15:24 UTC, ovh-cds commented
CDS Report build-all-cds#16101.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-06-11 08:44 UTC, ovh-cds commented
CDS Report build-all-cds#16134.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✘  
  * Test UI ✔

2021-06-11 09:15 UTC, fsamin approved these changes

2021-06-11 09:51 UTC, ovh-cds commented
CDS Report build-all-cds#16134.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-06-11 10:29 UTC, ovh-cds commented
CDS Report build-all-cds#16134.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-06-15 07:51 UTC, yesnault requested changes

2021-06-15 07:51 UTC, yesnault commented on contrib/integrations/artifactory/plugin-artifactory-release/main.go
> +		return fail("unable to create artifactory client")
```suggestion
		return fail("unable to create artifactory client: %v", err)
```

2021-06-15 07:51 UTC, yesnault commented on contrib/integrations/artifactory/plugin-artifactory-release/main.go
> +				skip = false
break missing

2021-06-15 08:04 UTC, richardlt approved these changes

2021-06-15 13:32 UTC, ovh-cds commented
CDS Report build-all-cds#16147.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-06-15 13:52 UTC, ovh-cds commented
CDS Report build-all-cds#16147.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-06-16 08:07 UTC, yesnault approved these changes

2021-06-16 08:07 UTC, merged