docs: disable and remove cdn unit
ovh/cds pull request #5853
Opened 2021-06-18 13:46 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-06-18 14:45 UTC, yesnault requested changes

2021-06-18 14:45 UTC, yesnault commented on docs/content/hosting/upgrade/migrate_0.49.md
> +* Remove the unit using cdsclt
```suggestion
* Remove the unit using cdsctl
```

2021-06-18 15:45 UTC, ovh-cds commented
CDS Report build-all-cds#16166.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-06-21 14:07 UTC, richardlt approved these changes

2021-06-21 14:08 UTC, yesnault approved these changes

2021-06-21 14:08 UTC, fsamin approved these changes

2021-06-21 14:16 UTC, merged