feat(service): ability to set jaeger servicename
ovh/cds pull request #5938
Opened 2021-09-16 12:08 UTC by fsamin

Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

2021-09-16 12:54 UTC, ovh-cds commented
CDS Report build-all-cds#16472.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2021-09-16 15:53 UTC, yesnault requested changes

2021-09-16 15:53 UTC, yesnault commented on sdk/telemetry/types.go
> +			ServiceName         string  `toml:"ServiceName" default:"" json:"serviceName"`
```suggestion
			ServiceName         string  `toml:"serviceName" default:"" json:"serviceName"`
```

2021-09-17 10:00 UTC, sguiheux approved these changes

2021-09-17 12:32 UTC, yesnault approved these changes

2021-09-17 13:25 UTC, merged