feat: worker run-result add static-file
ovh/cds pull request #5941
Opened 2021-09-20 07:47 UTC by yesnault

2021-09-20 07:50 UTC, sguiheux approved these changes

2021-09-20 08:05 UTC, richardlt approved these changes

2021-09-20 08:22 UTC, ovh-cds commented
CDS Report build-all-cds#16492.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-22 08:13 UTC, fsamin requested changes

2021-09-22 08:13 UTC, fsamin commented on engine/worker/cmd_run_result.go
> +		remoteURL := args[1]
maybe we should check if it's a valid URL (url.Parse)

2021-09-22 08:13 UTC, fsamin commented on engine/worker/internal/handler_run_result.go
> +func addRunResultArtifactManagerHandler(ctx context.Context, wk *CurrentWorker) http.HandlerFunc {
can you write a unit test of this handler (like we have a few ones)

2021-09-22 10:02 UTC, ovh-cds commented
CDS Report build-all-cds#16519.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 09:24 UTC, richardlt approved these changes

2021-09-24 09:28 UTC, fsamin approved these changes

2021-09-30 09:03 UTC, merged