fix: remove default group
ovh/cds pull request #5956
Opened 2021-09-24 10:32 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-09-24 10:44 UTC, ovh-cds commented
CDS Report build-all-cds#16547.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 13:08 UTC, richardlt requested changes

2021-09-24 13:08 UTC, richardlt commented on engine/api/group.go
>  		if withoutDefault {
Is this filter still useful ?

2021-09-24 13:08 UTC, richardlt commented on engine/api/notification/permission.go
> -		if group.DefaultGroup != nil && group.DefaultGroup.ID == g.Group.ID {
Be careful removing this will allow sending notification on the "old" default group.

2021-09-24 13:19 UTC, ovh-cds commented
CDS Report build-all-cds#16549.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 13:21 UTC, sguiheux commented on engine/api/group.go
>  		if withoutDefault {
no :)

2021-09-24 13:42 UTC, ovh-cds commented
CDS Report build-all-cds#16550.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 14:00 UTC, ovh-cds commented
CDS Report build-all-cds#16551.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 14:48 UTC, yesnault approved these changes

2021-09-24 14:52 UTC, ovh-cds commented
CDS Report build-all-cds#16553.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-09-24 15:26 UTC, richardlt approved these changes

2021-09-24 16:13 UTC, ovh-cds commented
CDS Report build-all-cds#16553.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-09-29 10:03 UTC, ovh-cds commented
CDS Report build-all-cds#16553.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-10-01 13:32 UTC, fsamin approved these changes

2021-10-01 13:36 UTC, merged