feat(worker): execute worker hooks
ovh/cds pull request #6004
Opened 2021-11-09 16:27 UTC by fsamin

Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

2021-11-09 16:36 UTC, sguiheux requested changes

2021-11-09 16:36 UTC, sguiheux commented on engine/worker/internal/run.go
> +				return errors.Errorf("unable to setup hook %q: %v", hookFilePath, err)
hookFile.Close?

2021-11-09 16:36 UTC, sguiheux commented on engine/worker/internal/run.go
> +				return errors.Errorf("unable to setup hook %q: %v", hookFilePath, err)
hookFile.close?

2021-11-09 16:40 UTC, fsamin commented on engine/worker/internal/run.go
> +				return errors.Errorf("unable to setup hook %q: %v", hookFilePath, err)
yes, just below

2021-11-09 16:41 UTC, fsamin commented on engine/worker/internal/run.go
> +				return errors.Errorf("unable to setup hook %q: %v", hookFilePath, err)
yes just below

2021-11-09 17:32 UTC, ovh-cds commented
CDS Report build-all-cds#16765.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2021-11-10 15:59 UTC, yesnault approved these changes

2021-11-12 10:46 UTC, sguiheux approved these changes

2021-11-12 10:47 UTC, merged