fix(api): validate username with regex
ovh/cds pull request #6026
Opened 2021-11-29 09:02 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-11-29 09:06 UTC, sguiheux requested changes

2021-11-29 09:06 UTC, sguiheux commented on sdk/user.go
> +		return NewErrorFrom(ErrInvalidUsername, "invalid given username")
```suggestion
		return NewErrorFrom(ErrInvalidUsername, "invalid given username: %s", username)
```

2021-11-29 09:06 UTC, sguiheux commented on engine/api/user/dao.go
>  		return sdk.WithStack(sdk.ErrInvalidUsername)
```suggestion
		return err
```

2021-11-29 09:06 UTC, sguiheux commented on engine/api/user/dao.go
> +		return sdk.WithStack(sdk.ErrInvalidUsername)
```suggestion
		return err
```

2021-11-29 09:06 UTC, sguiheux commented on engine/api/authentication/local/dao_registration.go
>  		return sdk.WithStack(sdk.ErrInvalidUsername)
```suggestion
		return err
```

2021-11-29 09:19 UTC, ovh-cds commented
CDS Report build-all-cds#16836.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-11-29 14:07 UTC, yesnault approved these changes

2021-11-30 08:30 UTC, fsamin approved these changes

2021-12-01 13:25 UTC, sguiheux approved these changes

2021-12-03 09:15 UTC, merged