fix(api): always add log fields from auth middleware
ovh/cds pull request #6046
Opened 2021-12-23 16:23 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2021-12-23 16:34 UTC, yesnault approved these changes

2021-12-23 16:40 UTC, ovh-cds commented
CDS Report build-all-cds#16941.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2021-12-27 09:05 UTC, fsamin requested changes

2021-12-27 09:05 UTC, fsamin commented on engine/worker/internal/run.go
> +					if !sdk.IsInArray(k+"="+v, w.Environ()) {
compute only once w.Environ() for all the scans

2021-12-27 09:17 UTC, fsamin approved these changes

2021-12-27 10:08 UTC, merged