fix(contrib): fail if there is no artifacts on a release
ovh/cds pull request #6073
Opened 2022-01-28 09:05 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-01-28 14:20 UTC, fsamin approved these changes

2022-01-31 10:03 UTC, yesnault requested changes

2022-01-31 10:03 UTC, yesnault commented on contrib/integrations/artifactory/plugin-artifactory-release/main.go
> +		return fail("There is no artifacts to release.")
```suggestion
		return fail("There is no artifact to release.")
```

2022-01-31 10:04 UTC, yesnault approved these changes

2022-01-31 16:19 UTC, richardlt approved these changes

2022-01-31 16:19 UTC, merged