feat(ui): allow to enter group name manually for project
ovh/cds pull request #6096
Opened 2022-02-23 09:43 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-02-23 10:02 UTC, ovh-cds commented
CDS Report build-all-cds#17093.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2022-02-23 13:45 UTC, yesnault approved these changes

2022-02-24 10:02 UTC, sguiheux requested changes

2022-02-24 10:02 UTC, sguiheux commented on ui/src/app/shared/permission/form/workflow-permission.form.html
> +            <sm-select class="fluid search" [options]="{'fullTextSearch': true}"
sui-select ?

2022-02-28 10:47 UTC, fsamin approved these changes

2022-02-28 11:04 UTC, ovh-cds commented
CDS Report build-all-cds#17102.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔

2022-02-28 13:21 UTC, sguiheux approved these changes

2022-02-28 13:50 UTC, ovh-cds commented
CDS Report build-all-cds#17104.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-02-28 15:12 UTC, merged