chore: Dockerfile from debian:bullseye-slim
ovh/cds pull request #6098
Opened 2022-02-25 14:24 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2022-02-25 14:24 UTC, sguiheux approved these changes

2022-02-25 14:26 UTC, richardlt approved these changes

2022-02-25 14:46 UTC, fsamin requested changes

2022-02-25 14:46 UTC, fsamin commented on Dockerfile
>      mkdir -p /app/sql /app/ui_static_files /app/panic_dumps
```suggestion
RUN apt-get update && \
    apt-get install -y curl ca-certificates gpg git && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /app/sql /app/ui_static_files
```

2022-02-25 15:16 UTC, ovh-cds commented
CDS Report build-all-cds#17100.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2022-02-25 15:49 UTC, richardlt approved these changes

2022-02-25 18:01 UTC, ovh-cds commented
CDS Report build-all-cds#17101.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-03-01 10:07 UTC, fsamin approved these changes

2022-03-01 10:07 UTC, richardlt approved these changes

2022-03-01 10:08 UTC, merged