feat: add rbac middleware system
ovh/cds pull request #6103
Opened 2022-03-02 16:19 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-03-02 16:27 UTC, fsamin requested changes

2022-03-02 16:27 UTC, fsamin commented on engine/service/http.go
> +type RbacChecker func(ctx context.Context, db *gorp.DbMap, vars map[string]string) error
*gorp.DbMap => SqlExecutor

2022-03-02 16:27 UTC, fsamin commented on engine/api/router_middleware_rbac.go
> +		if err := checker(ctx, api.mustDB(), mux.Vars(req)); err != nil {
for log purpose, add the name of the checker func as log field

2022-03-02 16:27 UTC, fsamin commented on engine/api/router_middleware_rbac.go
> +			return ctx, err
craft a 403 error

2022-03-02 16:27 UTC, fsamin commented on engine/api/v2_project.go
> +func (api *API) addVCSOnProjectHandler() (service.Handler, []service.RbacChecker) {
it's time to implement a first unit test

2022-03-02 16:27 UTC, fsamin commented on engine/api/rbac/project.go
> +	log.Debug(ctx, "Rbac.ProjectExist")
remove this log and add the name of the checker as field of the log (see below)

2022-03-03 09:47 UTC, fsamin approved these changes

2022-03-04 08:09 UTC, richardlt approved these changes

2022-03-04 08:54 UTC, ovh-cds commented
CDS Report build-all-cds#17135.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-03-11 13:14 UTC, ovh-cds commented
CDS Report build-all-cds#17146.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✘  
  * Test SDK Rust ✔ 
  * Test UI ✔

2022-03-11 14:47 UTC, ovh-cds commented
CDS Report build-all-cds#17148.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-03-14 09:01 UTC, fsamin requested changes
`+ sed s/Rbac/RBAC/`

2022-03-14 09:02 UTC, richardlt requested changes

2022-03-14 09:27 UTC, yesnault requested changes

2022-03-14 09:27 UTC, yesnault commented on sdk/rbac_project_test.go
> +	require.Contains(t, err.Error(), "Rbac myRule: role createProject is not allowed on a project permission")
```suggestion
	require.Contains(t, err.Error(), fmt.Sprintf("Rbac myRule: role %s is not allowed on a project permission", RoleCreateProject))
```

2022-03-14 09:29 UTC, sguiheux commented on engine/api/rbac/dao_rbac.go
> +	if _, err := db.Select(&projects, query, role, userID); err != nil {
I have to move this one in project dao

2022-03-14 09:35 UTC, sguiheux commented on engine/api/rbac/rbac.go
> +func fillRbacProjectWithID(ctx context.Context, db gorp.SqlExecutor, rbacPrj *sdk.RbacProject, projectCache map[string]int64, userCache map[string]string, groupCache map[string]int64) error {
no, function is test and assert through rbac loader

2022-03-14 09:48 UTC, sguiheux commented on engine/api/rbac/dao_rbac_project.go
> +	prjs, err := project.LoadProjectByRbacProject(ctx, db, rbacProject.ID)
not for project but ok

2022-03-14 09:58 UTC, sguiheux commented on engine/api/group/dao_rbac.go
> +func LoadGroupByRbacGlobal(ctx context.Context, db gorp.SqlExecutor, rbacGlobalID int64) ([]sdk.Group, error) {
Need all to check signature

2022-03-14 09:59 UTC, sguiheux commented on engine/api/user/dao_rbac.go
> +func LoadUsersByRbacProject(ctx context.Context, db gorp.SqlExecutor, rbacProjectID int64) ([]sdk.AuthentifiedUser, error) {
Need all to check signature

2022-03-14 10:01 UTC, sguiheux commented on engine/api/v2_project.go
> +		log.Info(ctx, "My project: %s", pKey)
will be removed during handler implementation

2022-03-14 12:26 UTC, ovh-cds commented
CDS Report build-all-cds#17151.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-03-15 08:33 UTC, fsamin requested changes

2022-03-15 08:33 UTC, fsamin commented on engine/api/router_middleware_rbac.go
> +			log.Error(ctx, "%v", err)
log.ErrorWithStackTrace

2022-03-15 08:35 UTC, yesnault approved these changes

2022-03-15 08:37 UTC, fsamin approved these changes

2022-03-21 08:33 UTC, richardlt requested changes

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/dao_rbac_project_group.go
> +	return rbacGroupIDs, nil
Need filter to remove the entity with invalid signature.

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/dao_rbac_project_project.go
> +	return rbacProjectIdentifier, nil
Need filter to remove entity with invalid signature.

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/dao_rbac_project_user.go
> +	return rbacProjectUsers, nil
Need filter to remove entities with invalid signature

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +func (r rbac) Canonical() gorpmapper.CanonicalForms {
Add a line to check that field exists add compilation.

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Add a line to check that fields exists a compilation time.

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Check field exists.

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Check field exists

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Check that fields exists

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Check that fields exists

2022-03-21 08:33 UTC, richardlt commented on engine/api/rbac/gorp_model.go
> +	return []gorpmapper.CanonicalForm{
Check that field exists

2022-03-21 09:00 UTC, richardlt approved these changes

2022-03-21 09:25 UTC, ovh-cds commented
CDS Report build-all-cds#17174.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-03-21 10:55 UTC, merged