refactor: db settings
ovh/cds pull request #6222
Opened 2022-06-29 14:18 UTC by yesnault

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

2022-06-29 15:26 UTC, richardlt requested changes

2022-06-29 15:26 UTC, richardlt commented on engine/cmd_database.go
> +		MaxConn:        connFactory.DBTimeout,
```suggestion
		MaxConn:        connFactory.DBMaxConn,
```

2022-06-29 15:26 UTC, richardlt commented on engine/cmd_database.go
> +		Timeout:        connFactory.DBMaxConn,
```suggestion
		Timeout:        connFactory.DBTimeout,
```

2022-06-29 15:26 UTC, richardlt commented on engine/cmd_database.go
> +		MaxConn:        connFactory.DBTimeout,
```suggestion
		MaxConn:        connFactory.DBMaxConn,
```

2022-06-29 15:26 UTC, richardlt commented on engine/cmd_database.go
> +		Timeout:        connFactory.DBMaxConn,
```suggestion
		Timeout:        connFactory.DBTimeout,
```

2022-06-29 15:41 UTC, fsamin commented on engine/database/database.go
> +		return nil, fmt.Errorf("missing database infos")
```suggestion
		return nil, errors.Errorf("missing database infos")
```

2022-06-29 15:52 UTC, ovh-cds commented
CDS Report build-all-cds#17572.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2022-06-29 16:01 UTC, fsamin approved these changes

2022-07-01 07:20 UTC, richardlt approved these changes

2022-07-01 07:58 UTC, merged