feat(api,hooks): add v2 hook signature and github repository analysis
ovh/cds pull request #6255
Opened 2022-08-23 15:15 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-08-25 07:07 UTC, yesnault commented on engine/api/v2_project.go
> +				return sdk.NewErrorFrom(sdk.ErrWrongRequest, "this handler need the repository uuid")
```suggestion
				return sdk.NewErrorFrom(sdk.ErrWrongRequest, "this handler needs the repository uuid")
```

2022-08-25 07:08 UTC, yesnault approved these changes

2022-08-25 08:55 UTC, fsamin requested changes

2022-08-25 08:55 UTC, fsamin commented on engine/hooks/hooks_router.go
> +		ctx = context.WithValue(ctx, "body", body)
don't put the body in the context, you have to reset a readable body in the request itself

2022-08-25 08:55 UTC, fsamin commented on engine/hooks/hooks_router.go
> +		ctx = context.WithValue(ctx, "body", body)
same as below

2022-08-25 08:55 UTC, fsamin commented on engine/hooks/hooks_handlers.go
> +		body, ok := ctx.Value("body").([]byte)
read the body from the request (the middleware shouldn't mutate the request)

2022-08-25 09:19 UTC, sguiheux commented on engine/api/repository/dao_vcs_project_repository.go
> +func LoadRepositoryByID(ctx context.Context, db gorp.SqlExecutor, id string, opts ...gorpmapping.GetOptionFunc) (sdk.ProjectRepository, error) {
done

2022-08-25 09:26 UTC, sguiheux commented on engine/api/v2_project_repository.go
> +				HookSignKey: repo.HookSignKey,
done

2022-08-25 09:56 UTC, sguiheux commented on engine/hooks/hooks_router.go
> +		h := hmac.New(sha256.New, []byte(hook.HookSignKey))
5ms on a gitea event

2022-08-25 09:59 UTC, sguiheux commented on engine/hooks/hooks_router.go
> +		ctx = context.WithValue(ctx, "body", body)
done

2022-08-25 10:23 UTC, ovh-cds commented
CDS Report build-all-cds#17801.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2022-08-25 13:04 UTC, fsamin requested changes

2022-08-25 13:04 UTC, fsamin commented on engine/api/operation/operation.go
> +	_, next := telemetry.Span(ctx, "operation.Poll")
you should keep the context to use it later

2022-08-25 13:04 UTC, fsamin commented on engine/api/rbac/dao_rbac_project_key.go
> +	_, next := telemetry.Span(ctx, "rbac.HasRoleOnProjectAndUserID")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/repository/dao_vcs_project_repository.go
> +	_, next := telemetry.Span(ctx, "repository.LoadRepositoryByID")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/repository/dao_vcs_project_repository_analyze.go
> +	_, next := telemetry.Span(ctx, "repository.LoadRepositoryAnalysisById")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/user/dao_gpgkey.go
> +	_, next := telemetry.Span(ctx, "user.LoadGPGKeyByKeyID")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/v2_repository_analyze.go
> +	_, next := telemetry.Span(ctx, "api.getCdsFilesOnVCSDirectory")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/v2_repository_analyze.go
> +	_, next := telemetry.Span(ctx, "api.getCdsArchiveFileOnRepo")
keep the context

2022-08-25 13:04 UTC, fsamin commented on engine/api/vcs/dao_vcs_project.go
> +	_, next := telemetry.Span(ctx, "vcs.LoadVCSByID")
keep the context

2022-08-25 14:34 UTC, fsamin approved these changes

2022-08-26 07:09 UTC, richardlt approved these changes

2022-08-26 07:16 UTC, merged