feat(cli): add delete workflow run command
ovh/cds pull request #6273
Opened 2022-09-08 11:54 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-09-08 12:21 UTC, fsamin requested changes

2022-09-08 12:40 UTC, ovh-cds commented
CDS Report build-all-cds#17877.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-09-08 13:14 UTC, sguiheux commented on cli/cdsctl/workflow_run.go
> +			Name: "run-number",
We have nothing to do that with args on the cli.
Like the others command ( workflow stop etc.), it's still easy to write a for loop in bash

2022-09-08 13:20 UTC, yesnault approved these changes

2022-09-09 12:27 UTC, richardlt approved these changes

2022-09-09 12:50 UTC, fsamin commented on cli/cdsctl/workflow_run.go
> +			Name: "run-number",
fake news !

2022-09-09 13:42 UTC, ovh-cds commented
CDS Report build-all-cds#17894.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2022-09-09 15:58 UTC, ovh-cds commented
CDS Report build-all-cds#17898.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-09-12 07:06 UTC, fsamin approved these changes

2022-09-12 07:24 UTC, merged