fix(worker): interpolate pattern to be able to use variable
ovh/cds pull request #6274
Opened 2022-09-08 13:51 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-09-08 14:38 UTC, ovh-cds commented
CDS Report build-all-cds#17880.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2022-09-08 15:50 UTC, yesnault approved these changes

2022-09-09 12:25 UTC, richardlt approved these changes

2022-09-09 12:48 UTC, fsamin requested changes

2022-09-09 12:48 UTC, fsamin commented on engine/worker/internal/action/builtin_artifact_download.go
> +	interpolatedPattern, err := interpolate.Do(pattern, sdk.ParametersToMap(wk.Parameters()))
action parameter should be interpolated before. i think this it not the right fix

2022-09-13 14:59 UTC, closed without merging