feat(api,cli): add organization
ovh/cds pull request #6289
Opened 2022-09-19 10:16 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-09-19 10:33 UTC, ovh-cds commented
CDS Report build-all-cds#17937.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-09-19 11:48 UTC, fsamin approved these changes

2022-09-19 12:05 UTC, ovh-cds commented
CDS Report build-all-cds#17939.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-09-19 12:19 UTC, yesnault requested changes

2022-09-19 12:19 UTC, yesnault commented on tests/03_clictl_admin_organization.yml
> +- name: List all organization
```suggestion
- name: List all organizations
```

2022-09-19 12:19 UTC, yesnault commented on cli/cdsctl/admin_organization.go
> +	Aliases: []string{"org", "orga"},
```suggestion
	Aliases: []string{"org", "orga", "organizations"},
```

2022-09-19 12:41 UTC, ovh-cds commented
CDS Report build-all-cds#17940.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-09-19 13:46 UTC, yesnault approved these changes

2022-09-20 16:25 UTC, ovh-cds commented
CDS Report build-all-cds#17944.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-09-21 07:03 UTC, ovh-cds commented
CDS Report build-all-cds#17944.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-09-21 07:44 UTC, ovh-cds commented
CDS Report build-all-cds#17946.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2022-09-21 08:59 UTC, richardlt approved these changes

2022-09-21 12:10 UTC, merged