feat(api,cli): add CRUD v2 organization and region
ovh/cds pull request #6296
Opened 2022-09-21 12:36 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-09-21 13:34 UTC, ovh-cds commented
CDS Report build-all-cds#17954.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-09-22 07:58 UTC, yesnault approved these changes

2022-09-22 08:09 UTC, fsamin requested changes

2022-09-22 08:09 UTC, fsamin commented on engine/api/v2_region.go
> +	return service.RBAC(rbac.RegionManage),
i think we don't need access control to get this resource

2022-09-22 08:09 UTC, fsamin commented on engine/api/v2_region.go
> +	return service.RBAC(rbac.RegionManage),
i think we don't need access control to get this resource

2022-09-22 09:36 UTC, fsamin approved these changes

2022-09-22 12:19 UTC, richardlt approved these changes

2022-09-22 12:54 UTC, merged