fix #6313
ovh/cds pull request #6314
Opened 2022-10-01 05:24 UTC by chavacava

Signed-off-by: Salvador Cavadini <salvadorcavadini+github@gmail.com>

1. Fix a bug in the detection of hook duplication (dao.go) caused by a typo in a slice index
1. #6313 

@ovh/cds

2022-10-03 16:11 UTC, richardlt approved these changes

2022-10-21 07:19 UTC, yesnault requested changes

2022-10-21 07:19 UTC, yesnault commented on engine/api/workflow/dao.go
>  				}
```suggestion
			duplicateHookIdx = append(duplicateHookIdx, int64(j))
```

2022-10-21 07:21 UTC, yesnault requested changes

2022-10-21 07:21 UTC, yesnault commented on engine/api/workflow/dao.go
> +			duplicateHookIdx = append(duplicateHookIdx, int64(j))
```suggestion
			  duplicateHookIdx = append(duplicateHookIdx, int64(j))
```

2022-10-21 07:21 UTC, yesnault approved these changes

2022-10-21 07:29 UTC, sguiheux approved these changes

2022-11-03 07:33 UTC, closed without merging