📝 README typos fix
ovh/cds pull request #6315
Opened 2022-10-01 10:10 UTC by barbadurkel

1. Description
Fixed some typos in README file.

@ovh/cds

2022-10-03 06:53 UTC, sguiheux approved these changes

2022-10-03 08:37 UTC, yesnault requested changes
Hi @barbadurkel, thank you for this PR. Can you signed off your commit please (see DCO check)?

2022-10-03 16:10 UTC, richardlt approved these changes

2022-10-03 19:45 UTC, barbadurkel commented
@yesnault, done.

2022-10-04 10:01 UTC, yesnault approved these changes

2022-10-10 16:02 UTC, merged