feat(api): add crud hatchery and rbac (hatchery + region)
ovh/cds pull request #6339
Opened 2022-10-18 11:55 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-10-18 12:14 UTC, ovh-cds commented
CDS Report build-all-cds#18113.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-10-19 07:26 UTC, yesnault requested changes

2022-10-19 07:26 UTC, yesnault commented on docs/content/hosting/upgrade/migrate_0.53.md
> +As we are updating DB table around authentication consumer, you will need to completly shutdown your CDS instances and all µservices.
```suggestion
As we are updating DB table around authentication consumer, you will need to completely shutdown your CDS instances and all µservices.
```

2022-10-19 07:26 UTC, yesnault commented on docs/content/hosting/upgrade/migrate_0.53.md
> +* Start the others µservices
```suggestion
* Start other µservices 
```

2022-10-19 07:26 UTC, yesnault commented on docs/content/hosting/upgrade/migrate_0.53.md
> +  * Migration can take a few minutes(between 1 and 5) depending on the number of users you have.
```suggestion
  * Migration can take a few minutes (between 1 and 5) depending on the number of users you have.
```

2022-10-19 07:26 UTC, yesnault commented on docs/content/hosting/upgrade/migrate_0.53.md
> +* Start 1 (scale to 1 if you usually use multiple instances) CDS API, check if there is no error on migration, with cdsctl admin migration list
```suggestion
* Start 1 (scale to 1 if you usually use multiple instances) CDS API, check if there is no error on migration, with `cdsctl admin migration list`
```

2022-10-19 08:17 UTC, ovh-cds commented
CDS Report build-all-cds#18118.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-10-19 08:45 UTC, yesnault approved these changes

2022-10-20 13:28 UTC, richardlt approved these changes

2022-10-20 14:07 UTC, ovh-cds commented
CDS Report build-all-cds#18127.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-10-24 07:54 UTC, fsamin requested changes

2022-10-24 07:54 UTC, fsamin commented on engine/api/rbac/rule_region.go
> +	log.RegisterField(LogFieldRole)
try to registerField only once (registering is playing with a mutex)

2022-10-24 07:54 UTC, fsamin commented on engine/api/v2_region.go
> +				rbacRegions, err := rbac.LoadRegionIDsByRoleAndUserID(ctx, api.mustDB(), sdk.RegionRoleRead, consumer.AuthConsumerUser.AuthentifiedUserID)
"Read a region" is a role ?

2022-10-24 07:54 UTC, fsamin commented on sdk/rbac.go
> +	HatcheryRoleSpawn = "spawn"
start worker ?

2022-10-24 07:54 UTC, fsamin commented on sdk/rbac.go
> +	RegionRoleRead   = "read"
what are we able to do when we "read" a region ?

2022-10-24 07:54 UTC, fsamin commented on sdk/rbac.go
> +	RegionRoleUse    = "use"
execute jobs ?

2022-10-24 08:38 UTC, sguiheux commented on sdk/rbac.go
> +	RegionRoleUse    = "use"
=> execute

2022-10-24 12:21 UTC, sguiheux commented on engine/api/v2_region.go
> +				rbacRegions, err := rbac.LoadRegionIDsByRoleAndUserID(ctx, api.mustDB(), sdk.RegionRoleRead, consumer.AuthConsumerUser.AuthentifiedUserID)
replace by list

2022-10-24 12:25 UTC, fsamin approved these changes

2022-10-24 12:41 UTC, ovh-cds commented
CDS Report build-all-cds#18145.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2022-10-24 13:53 UTC, merged