feat(api): add hatchery consumer
ovh/cds pull request #6350
Opened 2022-10-24 15:01 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-10-26 09:17 UTC, yesnault requested changes

2022-10-26 09:17 UTC, yesnault commented on engine/hatchery/vsphere/hatchery.go
> +	cfg.V2Token = sConfig.API.Token
```suggestion
	cfg.TokenV2 = sConfig.API.Token
```

2022-10-26 16:09 UTC, ovh-cds commented
CDS Report build-all-cds#18158.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2022-10-27 06:38 UTC, yesnault approved these changes

2022-10-27 06:54 UTC, richardlt requested changes

2022-10-27 06:54 UTC, richardlt commented on engine/api/api_routes.go
> +	r.Handle("/auth/consumer/hatchery/signin", ScopeNone(), r.POSTv2(api.postAuthHatcherySigninHandler, service.OverrideAuth(service.NoAuthMiddleware), MaintenanceAware()))
Not in v2 ?

2022-10-27 06:54 UTC, richardlt commented on engine/api/authentication/consumer.go
> -			ValidityPeriods: sdk.NewAuthConsumerValidityPeriod(time.Now(), 24*time.Hour),
Why do we remove this validity period ?

2022-10-27 06:54 UTC, richardlt commented on engine/api/authentication/dao_hatchery_consumer.go
> +		return nil, err
err is nil here but should not, do not log.Error but return the error

2022-10-27 06:54 UTC, richardlt commented on engine/api/authentication/hatchery/hatchery.go
> +var SessionDuration = 365 * 24 * time.Hour
Currently 1 h, we should not keep the session for 1 year

2022-10-27 06:54 UTC, richardlt commented on engine/hatchery/serve.go
> +	if c.PrivateKey != nil {
Should never be nil

2022-10-27 07:12 UTC, richardlt approved these changes

2022-10-27 07:59 UTC, ovh-cds commented
CDS Report build-all-cds#18163.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-10-27 08:55 UTC, ovh-cds commented
CDS Report build-all-cds#18164.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-10-27 09:55 UTC, ovh-cds commented
CDS Report build-all-cds#18166.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2022-10-27 12:09 UTC, merged