feat(hatchery): add hatchery heartbeat
ovh/cds pull request #6351
Opened 2022-10-27 12:33 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2022-10-27 12:36 UTC, yesnault approved these changes

2022-10-27 12:38 UTC, richardlt approved these changes

2022-11-03 08:32 UTC, fsamin requested changes

2022-11-03 08:32 UTC, fsamin commented on engine/api/v2_hatchery.go
> +func (api *API) postHatcheryHeartbeatHandler() ([]service.RbacChecker, service.Handler) {
add a new test

2022-11-03 11:05 UTC, fsamin approved these changes

2022-11-03 12:46 UTC, merged