Improve documentation for variables/params
ovh/cds pull request #6387
Opened 2022-12-08 16:56 UTC by moutyque

It was hard to find how to add a pipeline parameters and modify it inside a workflow and to use a cds vars as a value inside the workflow. I added element to explain how to do it.

@ovh/cds

2022-12-14 14:12 UTC, sguiheux approved these changes

2022-12-14 16:19 UTC, moutyque commented on docs/content/docs/concepts/variables.md
> +tags: ["variable", "variables", "helper", "helpers", "interpolate", ,"parameters","parameters"]
I still want the plural form of parameter as it is the case for variable

2022-12-14 16:23 UTC, moutyque commented
I amend the commit because I change some line formatting by mistake.

2022-12-27 12:15 UTC, yesnault requested changes

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +~~~
```yml
name: test-workflow
version: v2.0
workflow:
  the-pipeline:
    pipeline: build
    parameters:
      varname: the-value
...
```

You can use a Git or Builtin variable. example:

```yml
name: test-workflow
version: v2.0
workflow:
  the-pipeline:
    pipeline: build
    parameters:
      varname: {{.cds.version}}
...
```

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +~~~
```suggestion
```yaml
version: v1.0
name: build

parameters:
  param_name:
    type: string
    default: default_value

stages:
  ...
```
```

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.varname}}` in your pipeline.
```suggestion
On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.param_name}}` in your pipeline.
```

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.varname}}` in your pipeline.
```suggestion
On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.param_name}}` in your pipeline.
```

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.varname}}` in your pipeline.
```suggestion
On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.param_name}}` in your pipeline.
```

2022-12-27 12:15 UTC, yesnault commented on docs/content/docs/concepts/variables.md
> +This will let you to use `{{.cds.pip.varname}}` in your pipeline.
```suggestion
```

2023-01-03 08:59 UTC, moutyque commented on docs/content/docs/concepts/variables.md
> +This will let you to use `{{.cds.pip.varname}}` in your pipeline.
Why do you want to remove this line ?

2023-01-03 09:04 UTC, moutyque commented
I applied the comments.
Please review.

2023-01-04 08:16 UTC, yesnault commented
> I applied the comments. Please review.

it's a already here, with `On a pipeline, you can add some parameters, this will let you to use `{{.cds.pip.param_name}}` in your pipeline.` above, with the yml example containing param_name

2023-01-04 08:17 UTC, yesnault approved these changes

2023-01-04 08:18 UTC, merged