feat(api): add role mange-worker-model
ovh/cds pull request #6413
Opened 2023-01-09 16:53 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-01-09 17:15 UTC, ovh-cds commented
CDS Report build-all-cds#18383.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-01-10 11:11 UTC, ovh-cds commented
CDS Report build-all-cds#18387.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-01-10 13:52 UTC, ovh-cds commented
CDS Report build-all-cds#18388.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-01-11 13:24 UTC, richardlt requested changes

2023-01-11 13:24 UTC, richardlt commented on engine/api/v2_rbac.go
> +func (a *API) FillRBACWithNames(ctx context.Context, r *sdk.RBAC) error {
This looks like loader func in dao, can we move this functions on a dedicated struct that can be RBACLoader, this struct can also contains the map used to cache groups, users, etc.

2023-01-12 08:35 UTC, yesnault approved these changes

2023-01-13 09:49 UTC, richardlt approved these changes

2023-01-13 09:57 UTC, fsamin requested changes

2023-01-13 09:57 UTC, fsamin commented on sdk/rbac.go
> +	Globals      []RBACGlobal   `json:"globals,omitempty" db:"-"`
```suggestion
	Global      []RBACGlobal   `json:"global,omitempty" db:"-"`
```

2023-01-16 09:10 UTC, fsamin approved these changes

2023-01-16 09:27 UTC, merged