docs: add rbac and organization
ovh/cds pull request #6420
Opened 2023-01-16 15:49 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-01-17 08:13 UTC, yesnault requested changes

2023-01-17 08:13 UTC, yesnault commented on docs/content/docs/concepts/organization.md
> +Organization represents an organisational group that contains a set of people.
```suggestion
Organization represents an organizational group that contains a set of people.
```

2023-01-17 08:13 UTC, yesnault commented on docs/content/docs/concepts/organization.md
> +* a group belongs to only one organization. You cannot have users from different organizations in the same group
```suggestion
* a group belongs to only one organization. You cannot have users from different organizations in the same group.
```

2023-01-17 08:13 UTC, yesnault commented on docs/content/docs/concepts/rbac/global.md
> +title: "Global role"
```suggestion
title: "Global roles"
```

2023-01-17 08:13 UTC, yesnault commented on docs/content/docs/concepts/rbac/project.md
> +title: "Project role"
```suggestion
title: "Project roles"
```

2023-01-17 08:28 UTC, richardlt approved these changes

2023-01-18 08:46 UTC, yesnault approved these changes

2023-01-18 08:47 UTC, fsamin approved these changes

2023-01-18 08:52 UTC, merged