Add optional information for steps
ovh/cds pull request #6423
Opened 2023-01-18 10:06 UTC by moutyque

I could not find documentation about optional args on a step so I amend the documentation.

2023-01-18 10:13 UTC, sguiheux requested changes

2023-01-18 10:13 UTC, sguiheux commented on docs/content/docs/concepts/files/pipeline-syntax.md
> +It is possible to make a step optional. Even if this task fail the pipeline will continue.
```suggestion
It is possible to make a step optional. Even if this task fail the job will continue.
```

2023-01-19 14:05 UTC, sguiheux approved these changes

2023-02-02 13:33 UTC, richardlt approved these changes

2023-02-02 13:34 UTC, merged