Add uuidv4 helper function
ovh/cds pull request #6438
Opened 2023-02-02 14:53 UTC by sixstone-qq

1. Description

Using ovh/venom, I found the variables helpers are not using latest version
from `Masterminds/sprig` package so I backported the one that could be really
useful (`uuidv4` generation) here.

Taken from
https://github.com/Masterminds/sprig/blob/3ac42c7bc5e4be6aa534e036fb19dde4a996da2e/functions.go#L355

1. Related issues

I didn't use `sdk.UUID()` because it's a different package and I see there is a
different Go module.

Let me know what you think.

1. About tests
1. Mentions

@ovh/cds

2023-02-06 09:08 UTC, richardlt commented
Should be possible to reuse sdk.UUID() rather than importing a new lib.

2023-02-06 09:09 UTC, richardlt requested changes
Should be possible to reuse sdk.UUID() rather than importing a new lib.

2023-02-06 14:12 UTC, yesnault commented
Hi, you can define helper into venom only, not needed to add it into cds.

2023-02-06 14:12 UTC, closed without merging

2023-02-08 12:52 UTC, sixstone-qq commented
> Hi, you can define helper into venom only, not needed to add it into cds.

Thanks a lot for your response, I'd like to include all new functions from https://github.com/Masterminds/sprig but this is not currently possible to only do that in venom because `template.FuncMap` is being wrapper with [wrapHelpers](https://github.com/ovh/cds/blob/master/sdk/interpolate/interpolate_helper.go#L86) function which is private so I can't override `InterpolateHelperFuncs` function. Which action path do you suggest me to follow?

Thanks a lot!