feat(sdk): add os/arch on worker model v2
ovh/cds pull request #6446
Opened 2023-02-08 06:46 UTC by richardlt

Signed-off-by: richardlt <richard.le.terrier@gmail.com>

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-02-08 13:46 UTC, sguiheux requested changes

2023-02-09 11:00 UTC, richardlt commented on sdk/jsonschema.go
> +	wmSchema.Definitions["V2WorkerModel"].Required = append(wmSchema.Definitions["V2WorkerModel"].Required, "osarch")
Done

2023-02-09 15:15 UTC, sguiheux approved these changes

2023-02-09 15:15 UTC, yesnault approved these changes

2023-02-09 15:16 UTC, fsamin approved these changes

2023-02-09 15:17 UTC, merged