fix(api): add logs for vcs status debug
ovh/cds pull request #6486
Opened 2023-02-24 15:08 UTC by fsamin

2023-02-24 15:10 UTC, sguiheux requested changes

2023-02-24 15:10 UTC, sguiheux commented on engine/api/workflow/workflow_run_event.go
> +	log.Info(ctx, "Send status %q for node run %d", nodeRun.ID, nodeRun.Status)
wrong param order

2023-02-24 15:17 UTC, sguiheux approved these changes

2023-03-01 08:59 UTC, yesnault approved these changes

2023-03-01 08:59 UTC, merged