feat(api): execute ascode action
ovh/cds pull request #6523
Opened 2023-03-29 12:57 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-03-29 13:21 UTC, ovh-cds commented
CDS Report build-all-cds#18709.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-03-30 10:57 UTC, ovh-cds commented
CDS Report build-all-cds#18713.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-03-30 12:23 UTC, ovh-cds commented
CDS Report build-all-cds#18714.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-03-30 15:02 UTC, ovh-cds commented
CDS Report build-all-cds#18717.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-03-31 07:27 UTC, ovh-cds commented
CDS Report build-all-cds#18718.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-04-03 07:12 UTC, yesnault requested changes

2023-04-03 07:12 UTC, yesnault commented on engine/api/v2_repository_analyze.go
> +			analysis.Data.Error = "no files found"
```suggestion
			analysis.Data.Error = "no file found"
```

2023-04-03 07:12 UTC, yesnault commented on sdk/exportentities/step.go
> +	AsCodeAction     *StepAscodeAction     `json:"AsCodeAction,omitempty" yaml:"AsCodeAction,omitempty" jsonschema:"oneof_required=AsCodeAction" jsonschema_description:"ascode action"`
```suggestion
	AsCodeAction     *StepAscodeAction     `json:"asCodeAction,omitempty" yaml:"asCodeAction,omitempty" jsonschema:"oneof_required=asCodeAction" jsonschema_description:"ascode action"`
```

2023-04-03 07:12 UTC, yesnault commented on sdk/workflowv3/step.go
> +	AsCodeAction              *exportentities.StepAscodeAction     `json:"AsCodeAction,omitempty" yaml:"AsCodeAction,omitempty"`
```suggestion
	AsCodeAction              *exportentities.StepAscodeAction     `json:"asCodeAction,omitempty" yaml:"asCodeAction,omitempty"`
```

2023-04-03 07:15 UTC, yesnault requested changes

2023-04-03 07:15 UTC, yesnault commented on tests/fixtures/ITCLIPRJVCS/pipeline.pip.yml
> +    AsCodeAction:
```suggestion
    asCodeAction:
```

2023-04-03 14:22 UTC, fsamin approved these changes

2023-04-04 09:29 UTC, merged