refactor(worker): refact plugin & add script plugin
ovh/cds pull request #6527
Opened 2023-04-04 13:47 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-04-05 07:25 UTC, ovh-cds commented
CDS Report build-all-cds#18726.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-04-11 13:40 UTC, ovh-cds commented
CDS Report build-all-cds#18748.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-04-11 15:07 UTC, ovh-cds commented
CDS Report build-all-cds#18748.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ■   
  * Standalone Tests ■

2023-04-11 15:07 UTC, ovh-cds commented
CDS Report build-all-cds#18748.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ■   
  * Standalone Tests ■

2023-04-11 15:34 UTC, ovh-cds commented
CDS Report build-all-cds#18748.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-04-11 15:53 UTC, ovh-cds commented
CDS Report build-all-cds#18750.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-04-11 16:14 UTC, ovh-cds commented
CDS Report build-all-cds#18750.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2023-04-12 06:58 UTC, ovh-cds commented
CDS Report build-all-cds#18750.2 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ■   
  * Standalone Tests ■

2023-04-12 06:58 UTC, ovh-cds commented
CDS Report build-all-cds#18750.2 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ■   
  * Standalone Tests ■

2023-04-12 07:24 UTC, ovh-cds commented
CDS Report build-all-cds#18750.3 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2023-04-12 13:24 UTC, ovh-cds commented
CDS Report build-all-cds#18751.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-04-12 15:43 UTC, yesnault requested changes

2023-04-12 15:43 UTC, yesnault commented on contrib/grpcplugins/action/plugin-script/main.go
> +		//cmd.Env = wk.Environ()
```suggestion
		//cmd.Env = wk.Environ()
```

2023-04-12 15:43 UTC, yesnault commented on contrib/grpcplugins/action/plugin-script/main.go
> +		fmt.Printf("\"CDS Worker execution canceled: %v", ctx.Err())
```suggestion
		fmt.Printf("CDS Worker execution canceled: %v", ctx.Err())
```

2023-04-12 15:43 UTC, yesnault commented on engine/worker/internal/run_ascode.go
> +			stepName := prefixStepName + filepath.Base(actionName)
to recheck, probably missing '/'

2023-04-12 15:43 UTC, yesnault commented on engine/worker/internal/run_ascode.go
> +	// TODO Set input regarding plugin descriptor + interpoloate action params with context
TODO ?

2023-04-13 07:49 UTC, sguiheux commented on engine/worker/internal/run_ascode.go
> +			stepName := prefixStepName + filepath.Base(actionName)
prefix contains /

2023-04-13 12:51 UTC, richardlt commented on contrib/grpcplugins/action/plugin-archive/go.mod
> +	github.com/tebeka/go2xunit v1.4.10 // indirect
To remove

2023-04-13 12:52 UTC, richardlt commented on contrib/grpcplugins/action/plugin-archive/go.mod
> +	github.com/tebeka/go2xunit v1.4.10 // indirect
To remove

2023-04-13 12:52 UTC, richardlt commented on contrib/grpcplugins/action/plugin-archive/go.sum
> +github.com/tebeka/go2xunit v1.4.10 h1:0UO+9YoLpXTZ0DL9XbTmIIibgmKBGiwroo8uhFMSyR0=
To remove

2023-04-24 16:04 UTC, richardlt approved these changes

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +		return nil, fmt.Errorf("unable to start GRPCPlugin: %v", err)
```suggestion
		return nil, errors.Errorf("unable to start GRPCPlugin: %v", err)
```

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to call GRPCPlugin: %v", err)
```suggestion
			return nil, errors.Errorf("unable to call GRPCPlugin: %v", err)
```

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to setup plugin with worker port: %v", err)
```suggestion
			return nil, errors.Errorf("unable to setup plugin with worker port: %v", err)
```

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to call GRPCPlugin: %v", err)
```suggestion
			return nil, errors.Errorf("unable to call GRPCPlugin: %v", err)
```

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to setup plugin with worker port: %v", err)
```suggestion
			return nil, errors.Errorf("unable to setup plugin with worker port: %v", err)
```

2023-04-25 08:01 UTC, fsamin commented on engine/worker/internal/plugin/plugin.go
> +		return nil, fmt.Errorf("unable to retrieve retrieve plugin manifest: %v", err)
```suggestion
		return nil, errors.Errorf("unable to retrieve retrieve plugin manifest: %v", err)
```

2023-04-25 08:23 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +	go func() {
done

2023-04-25 08:27 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +		go func() {
done

2023-04-25 08:33 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +		return nil, fmt.Errorf("working directory %s is not a directory: %v", script.dir, err)
done

2023-04-25 08:33 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +		return nil, err
done

2023-04-25 08:34 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +		return nil, fmt.Errorf("cannot create temporary file, aborting: %v", err)
done

2023-04-25 08:36 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +			return nil, fmt.Errorf("unable to create script: %v", err)
done

2023-04-25 08:37 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +			return nil, fmt.Errorf("unable to write all script: %d/%d", n, len(script.content))
done

2023-04-25 08:38 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-script/main.go
> +			return nil, fmt.Errorf("unable to get script working dir: %v", err)
done

2023-04-25 08:39 UTC, sguiheux commented on contrib/grpcplugins/grpcplugins.go
> +		return nil, fmt.Errorf("worker port must not be 0")
done

2023-04-25 08:40 UTC, sguiheux commented on contrib/grpcplugins/grpcplugins.go
> +		return nil, fmt.Errorf("unable to create request to get directories: %v", err)
done

2023-04-25 08:40 UTC, sguiheux commented on contrib/grpcplugins/grpcplugins.go
> +		return nil, fmt.Errorf("cannot get run result directories: %v", err)
done

2023-04-25 08:40 UTC, sguiheux commented on contrib/grpcplugins/grpcplugins.go
> +		return nil, fmt.Errorf("cannot get working directory: HTTP %d", resp.StatusCode)
done

2023-04-25 08:41 UTC, sguiheux commented on contrib/grpcplugins/grpcplugins.go
> +		return nil, fmt.Errorf("unable to unmarshal response: %v", err)
done

2023-04-25 08:42 UTC, sguiheux commented on engine/worker/internal/plugin/plugin.go
> +		return nil, fmt.Errorf("unable to start GRPCPlugin: %v", err)
done

2023-04-25 08:42 UTC, sguiheux commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to call GRPCPlugin: %v", err)
done

2023-04-25 08:43 UTC, sguiheux commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to setup plugin with worker port: %v", err)
done

2023-04-25 08:43 UTC, sguiheux commented on engine/worker/internal/plugin/plugin.go
> +			return nil, fmt.Errorf("unable to setup plugin with worker port: %v", err)
done

2023-04-25 08:44 UTC, sguiheux commented on engine/worker/internal/plugin/plugin.go
> +		return nil, fmt.Errorf("unable to retrieve retrieve plugin manifest: %v", err)
done

2023-04-25 09:57 UTC, fsamin approved these changes

2023-04-25 12:24 UTC, merged