docs(cdsctl): download from ui
ovh/cds pull request #6534
Opened 2023-04-13 11:08 UTC by yesnault

2023-04-13 12:16 UTC, richardlt approved these changes

2023-04-13 12:17 UTC, sguiheux approved these changes

2023-04-17 16:37 UTC, richardlt approved these changes

2023-04-17 16:39 UTC, richardlt requested changes

2023-04-17 16:39 UTC, richardlt commented on cli/cdsctl/main.go
> +You can find the cdstl version corresponding to your CDS version on the ui: Menu -> Settings -> Command line cdsctl. This page will inform you how to configure your cdsctl according to your cds insta
```suggestion
You can find the cdsctl version corresponding to your CDS version on the UI: Menu -> Settings -> Command line cdsctl. You'll also find the instructions to configure your cdsctl according to your CDS instance.
```

2023-04-20 12:47 UTC, richardlt approved these changes

2023-04-20 12:50 UTC, ovh-cds commented
CDS Report build-all-cds#18781.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

2023-04-20 12:50 UTC, ovh-cds commented
CDS Report build-all-cds#18781.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ■   
  * Build SMTPMock ■   
  * Lint UI Translate ✔ 
  * Test CLI ■   
  * Test Engine ■   
  * Test SDK ■   
  * Test UI ■

2023-04-21 07:17 UTC, merged