feat(api,hatchery): allow hatchery to handle jobrun
ovh/cds pull request #6578
Opened 2023-06-28 08:16 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-06-28 09:00 UTC, ovh-cds commented
CDS Report build-all-cds#18936.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-03 07:16 UTC, richardlt approved these changes

2023-07-03 07:25 UTC, yesnault requested changes

2023-07-03 07:25 UTC, yesnault commented on sdk/websocket.go
> +	RunNumber    int64
```suggestion
	JobRunID     string `json:"job_run_id"`
	Region       string `json:"region"`
	ModelType    string `json:"model_type"`
	ProjectKey   string `json:"project_key"`
	WorkflowName string `json:"workflow_name"`
	JobID        string `json:"job_id"`
	RunNumber    int64 `json:"run_number"`
```

2023-07-03 08:02 UTC, fsamin requested changes

2023-07-03 08:02 UTC, fsamin commented on engine/api/workflow_v2/dao_run_job_info.go
> +func getAllRunJobInfos(ctx context.Context, db gorp.SqlExecutor, query gorpmapping.Query) ([]sdk.V2WorkflowRunJobInfo, error) {
Information is uncountable in english

2023-07-03 14:18 UTC, sguiheux commented on engine/api/workflow_v2/dao_run_job_info.go
> +func getAllRunJobInfos(ctx context.Context, db gorp.SqlExecutor, query gorpmapping.Query) ([]sdk.V2WorkflowRunJobInfo, error) {
done

2023-07-03 14:18 UTC, sguiheux commented on engine/api/v2_workflow_run_engine.go
> +	// Send to websocket
done

2023-07-03 14:42 UTC, ovh-cds commented
CDS Report build-all-cds#18943.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-07-03 16:10 UTC, ovh-cds commented
CDS Report build-all-cds#18945.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✔

2023-07-04 07:30 UTC, yesnault approved these changes

2023-07-04 07:35 UTC, fsamin approved these changes

2023-07-05 12:45 UTC, ovh-cds commented
CDS Report build-all-cds#18951.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-07-07 15:08 UTC, ovh-cds commented
CDS Report build-all-cds#18970.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-07-10 08:06 UTC, merged