feat(hatchery): manage stirng jobID and ascode worker model
ovh/cds pull request #6584
Opened 2023-07-10 14:31 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-07-10 15:11 UTC, ovh-cds commented
CDS Report build-all-cds#18976.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2023-07-11 08:50 UTC, ovh-cds commented
CDS Report build-all-cds#18977.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-11 10:21 UTC, ovh-cds commented
CDS Report build-all-cds#18981.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-07-11 14:32 UTC, ovh-cds commented
CDS Report build-all-cds#18985.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2023-07-11 14:32 UTC, ovh-cds commented
CDS Report build-all-cds#18985.1 ■   
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ■

2023-07-12 08:33 UTC, ovh-cds commented
CDS Report build-all-cds#18989.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-07-12 13:28 UTC, ovh-cds commented
CDS Report build-all-cds#18991.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2023-07-13 14:49 UTC, yesnault approved these changes

2023-07-17 09:11 UTC, richardlt requested changes

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/vsphere/hatchery.go
> +	if jobID == "0" {
Convert to int then compare <= 0 ?

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/swarm/swarm.go
> +	if spawnArgs.JobID != "0" {
Same

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/swarm/swarm.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
Same

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/local/worker_spawn.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
Same

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/kubernetes/kubernetes.go
> +	if spawnArgs.JobID != "0" {
Same

2023-07-17 09:11 UTC, richardlt commented on engine/hatchery/kubernetes/kubernetes.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
Same

2023-07-17 09:32 UTC, sguiheux commented on engine/worker/internal/start.go
> +	if bookedJobID == "0" {
done

2023-07-17 09:36 UTC, sguiheux commented on sdk/hatchery/hatchery.go
> +	if h.CDSClient() == nil || jobID == "" {
fixed

2023-07-17 09:43 UTC, sguiheux commented on engine/hatchery/vsphere/hatchery.go
> +	if jobID == "0" {
done

2023-07-17 09:44 UTC, sguiheux commented on engine/hatchery/swarm/swarm.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
done

2023-07-17 09:44 UTC, sguiheux commented on engine/hatchery/local/worker_spawn.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
done

2023-07-17 09:45 UTC, sguiheux commented on engine/hatchery/kubernetes/kubernetes.go
> +	if spawnArgs.JobID != "0" {
done

2023-07-17 09:45 UTC, sguiheux commented on engine/hatchery/kubernetes/kubernetes.go
> +	if spawnArgs.JobID == "0" && !spawnArgs.RegisterOnly {
done

2023-07-17 10:10 UTC, ovh-cds commented
CDS Report build-all-cds#18998.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-07-18 06:51 UTC, merged