feat(api,worker): add worker job execution
ovh/cds pull request #6594
Opened 2023-07-24 08:48 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-07-24 09:19 UTC, ovh-cds commented
CDS Report build-all-cds#19031.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-24 09:38 UTC, ovh-cds commented
CDS Report build-all-cds#19031.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-24 09:55 UTC, ovh-cds commented
CDS Report build-all-cds#19031.2 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-25 10:14 UTC, ovh-cds commented
CDS Report build-all-cds#19033.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-25 15:51 UTC, yesnault requested changes

2023-07-25 15:51 UTC, yesnault commented on engine/api/v2_rbac_check.go
> +				return sdk.WrapError(sdk.ErrUnauthorized, "hatchery consumer cannot access proejct %s", checkRequest.ProjectKey)
```suggestion
				return sdk.WrapError(sdk.ErrUnauthorized, "hatchery consumer cannot access project %s", checkRequest.ProjectKey)
```

2023-07-25 15:51 UTC, yesnault commented on engine/worker/internal/action/test_helper.go
> +	panic("implement me")
return nil

2023-07-25 15:51 UTC, yesnault commented on engine/worker/internal/action/test_helper.go
> +	panic("implement me")
return nil

2023-07-25 16:21 UTC, ovh-cds commented
CDS Report build-all-cds#19037.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-26 07:27 UTC, yesnault approved these changes

2023-07-26 08:07 UTC, ovh-cds commented
CDS Report build-all-cds#19038.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-26 08:16 UTC, fsamin approved these changes

2023-07-26 08:38 UTC, ovh-cds commented
CDS Report build-all-cds#19039.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-26 09:09 UTC, ovh-cds commented
CDS Report build-all-cds#19039.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-07-26 15:15 UTC, yesnault approved these changes

2023-07-26 15:23 UTC, fsamin approved these changes

2023-07-26 15:26 UTC, ovh-cds commented
CDS Report build-all-cds#19045.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-07-27 07:50 UTC, ovh-cds commented
CDS Report build-all-cds#19052.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘

2023-07-27 12:04 UTC, merged