feat: add routines to handle lost run/jobs/workers
ovh/cds pull request #6598
Opened 2023-07-28 15:36 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-07-31 07:29 UTC, fsamin commented on engine/api/v2_workflow_run_job_routines.go
> +	log.Info(ctx, fmt.Sprintf("reEnqueueScheduledJob: re-enqueue job %s/%s on workflow %s run %d", runJob.JobID, runJob.ID, runJob.WorkflowName, runJob.RunNumber))
Add schedule time in the log

2023-07-31 08:39 UTC, ovh-cds commented
CDS Report build-all-cds#19067.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✘

2023-07-31 13:59 UTC, ovh-cds commented
CDS Report build-all-cds#19069.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-08-01 07:45 UTC, fsamin requested changes

2023-08-01 07:45 UTC, fsamin commented on engine/worker/internal/takeV2.go
> +				return
stop the ticker

2023-08-01 07:52 UTC, sguiheux commented on engine/worker/internal/takeV2.go
> +				return
done

2023-08-01 08:34 UTC, ovh-cds commented
CDS Report build-all-cds#19071.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-08-01 10:01 UTC, merged