feat(workflow v2): uploadArtifact
ovh/cds pull request #6676
Opened 2023-11-06 15:15 UTC by fsamin

2023-11-06 15:59 UTC, sguiheux requested changes

2023-11-06 15:59 UTC, sguiheux commented on contrib/grpcplugins/action/plugin-uploadArtifact/plugin-uploadArtifact.yml
> +    description: >
missing type ?

2023-11-06 15:59 UTC, sguiheux commented on engine/api/v2_workflow_run_engine.go
> +				if !jobDef.Integrations.IsEmpty() {
wrong place

2023-11-06 16:23 UTC, ovh-cds commented
CDS Report build-all-cds#19346.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-07 08:45 UTC, fsamin commented on engine/api/v2_workflow_run_engine.go
> +				if !jobDef.Integrations.IsEmpty() {
done

2023-11-07 09:20 UTC, ovh-cds commented
CDS Report build-all-cds#19348.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-07 10:24 UTC, ovh-cds commented
CDS Report build-all-cds#19350.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-07 10:48 UTC, ovh-cds commented
CDS Report build-all-cds#19350.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-07 14:43 UTC, sguiheux approved these changes

2023-11-07 15:39 UTC, ovh-cds commented
CDS Report build-all-cds#19353.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✘  
  * Test UI ✔

2023-11-07 18:12 UTC, ovh-cds commented
CDS Report build-all-cds#19355.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-11-08 09:24 UTC, yesnault approved these changes

2023-11-08 09:46 UTC, ovh-cds commented
CDS Report build-all-cds#19358.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✘  
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-11-08 11:03 UTC, merged