feat(worker): cds/git/env context as environment variable in plugin
ovh/cds pull request #6697
Opened 2023-11-21 16:22 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-11-21 16:37 UTC, ovh-cds commented
CDS Report build-all-cds#19479.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-11-21 17:16 UTC, ovh-cds commented
CDS Report build-all-cds#19480.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-22 08:37 UTC, ovh-cds commented
CDS Report build-all-cds#19480.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔ 
* Package
  * Docker ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘

2023-11-22 13:28 UTC, richardlt approved these changes

2023-11-28 08:13 UTC, yesnault requested changes

2023-11-28 08:13 UTC, yesnault commented on engine/worker/internal/runV2.go
> +		newEnvVar[fmt.Sprintf("GIT_%s", strings.ToUpper(k))] = fmt.Sprintf("%q", v)
```suggestion
		newEnvVar[fmt.Sprintf("GIT_%s", strings.ToUpper(k))] = fmt.Sprintf("%v", v)
```

2023-11-28 08:13 UTC, yesnault commented on engine/worker/internal/runV2.go
> +			newEnvVar[fmt.Sprintf("CDS_%s", strings.ToUpper(k))] = fmt.Sprintf("%q", v)
```suggestion
			newEnvVar[fmt.Sprintf("CDS_%s", strings.ToUpper(k))] = fmt.Sprintf("%v", v)
```

2023-11-28 08:13 UTC, yesnault commented on tests/08_v2_analyze.yml
> +    - script: "cat MyFirstWorkflow-1-0-alwaysJob-mystep | grep \"alwaysJob\""
```suggestion
    - script: "cat MyFirstWorkflow-1-0-alwaysJob-mystep | grep \"I am alwaysJob\""
```

2023-11-28 08:13 UTC, yesnault commented on engine/worker/internal/runV2.go
> +		newEnvVar[strings.ToUpper(k)] = fmt.Sprintf("%q", v)
```suggestion
		newEnvVar[strings.ToUpper(k)] = fmt.Sprintf("%v", v)
```

2023-11-28 08:31 UTC, ovh-cds commented
CDS Report build-cds#19558.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-28 08:58 UTC, ovh-cds commented
CDS Report build-cds#19559.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-28 09:26 UTC, ovh-cds commented
CDS Report integration-cds#19559.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-28 10:15 UTC, yesnault approved these changes

2023-11-28 10:26 UTC, merged