draft: rerun job failed
ovh/cds pull request #6698
Opened 2023-11-21 16:28 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-11-27 14:05 UTC, ovh-cds commented
CDS Report build-cds#19553.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-27 14:33 UTC, ovh-cds commented
CDS Report integration-cds#19553.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-11-27 15:22 UTC, ovh-cds commented
CDS Report build-cds#19554.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-27 15:45 UTC, ovh-cds commented
CDS Report integration-cds#19554.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-11-27 16:31 UTC, ovh-cds commented
CDS Report build-cds#19556.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-27 16:49 UTC, ovh-cds commented
CDS Report integration-cds#19556.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✘

2023-11-28 08:22 UTC, ovh-cds commented
CDS Report build-cds#19557.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-28 08:50 UTC, ovh-cds commented
CDS Report integration-cds#19557.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-11-28 09:33 UTC, ovh-cds commented
CDS Report integration-cds#19561.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-28 11:30 UTC, ovh-cds commented
CDS Report integration-cds#19565.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-11-28 13:15 UTC, ovh-cds commented
CDS Report build-cds#19566.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-28 13:44 UTC, ovh-cds commented
CDS Report integration-cds#19566.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-29 10:03 UTC, yesnault approved these changes

2023-11-29 15:20 UTC, ovh-cds commented
CDS Report build-cds#19566.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-29 15:20 UTC, ovh-cds commented
CDS Report integration-cds#19566.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-29 15:50 UTC, ovh-cds commented
CDS Report build-cds#19595.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-29 16:16 UTC, ovh-cds commented
CDS Report integration-cds#19595.0 ✘  
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-11-29 17:31 UTC, ovh-cds commented
CDS Report integration-cds#19595.1 ✘  
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-30 07:48 UTC, ovh-cds commented
CDS Report integration-cds#19595.2 ✘  
* Integration
  * Docker Compose Tests ✘  
  * Standalone Tests ✘  
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-11-30 08:14 UTC, fsamin requested changes

2023-11-30 08:14 UTC, fsamin commented on cli/cdsctl/experimental_workflow.go
> +	Name:    "rerun",
run, retry, restart

2023-11-30 08:14 UTC, fsamin commented on sdk/cdsclient/client_workflowv2.go
> +	path := fmt.Sprintf("/v2/project/%s/vcs/%s/repository/%s/workflow/%s/run/%d/rerun", projectKey, url.PathEscape(vcsIdentifier), url.PathEscape(repoIdentifier), wkfName, runNumber)
🤮

2023-11-30 08:14 UTC, fsamin commented on sdk/cdsclient/interface.go
> +	WorkflowV2ReRun(ctx context.Context, projectKey, vcsIdentifier, repoIdentifier, wkfName string, runNumber int64, mods ...RequestModifier) (*sdk.V2WorkflowRun, error)
🤢

2023-11-30 08:14 UTC, fsamin commented on tests/08_v2_rerun.yml
> +name: Checkout plugin
wrong name

2023-11-30 08:14 UTC, fsamin commented on tests/08_v2_rerun.yml
> +    - name: Rerun failed job
🤧

2023-11-30 08:18 UTC, richardlt approved these changes

2023-11-30 08:41 UTC, ovh-cds commented
CDS Report build-cds#19601.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-11-30 12:36 UTC, fsamin approved these changes

2023-11-30 12:43 UTC, merged