feat(sdk/interpolate) Add new math interpolations
ovh/cds pull request #6716
Opened 2023-12-05 10:10 UTC by bcecchinato

1. Description
2. Related issues
3. About tests
4. Mentions

@ovh/cds

2023-12-21 13:18 UTC, yesnault approved these changes

2023-12-21 13:51 UTC, ovh-cds commented
CDS Report build-cds#19756.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-21 13:52 UTC, ovh-cds commented
CDS Report build-cds#19759.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-21 14:08 UTC, ovh-cds commented
CDS Report build-cds#19759.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-21 14:35 UTC, ovh-cds commented
CDS Report integration-cds#19759.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-27 10:02 UTC, sguiheux requested changes

2023-12-27 10:02 UTC, sguiheux commented on sdk/interpolate/interpolate_test.go
> +			want:   "my value 4 4",
{{ div 2 2 }} => must be equal to 1

2024-01-03 10:05 UTC, ovh-cds commented
CDS Report build-cds#19803.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 10:30 UTC, ovh-cds commented
CDS Report integration-cds#19803.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-05 09:44 UTC, sguiheux approved these changes

2024-01-05 09:57 UTC, ovh-cds commented
CDS Report build-cds#19823.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-05 10:24 UTC, ovh-cds commented
CDS Report integration-cds#19823.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-05 10:46 UTC, merged