feat(workflowV2): support integration
ovh/cds pull request #6732
Opened 2023-12-13 14:48 UTC by fsamin

2023-12-13 14:56 UTC, richardlt approved these changes

2023-12-13 15:09 UTC, yesnault approved these changes

2023-12-13 15:11 UTC, ovh-cds commented
CDS Report build-cds#19702.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-13 16:49 UTC, ovh-cds commented
CDS Report build-cds#19703.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-13 17:16 UTC, ovh-cds commented
CDS Report integration-cds#19703.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-12-14 09:05 UTC, ovh-cds commented
CDS Report build-cds#19705.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-14 09:30 UTC, ovh-cds commented
CDS Report integration-cds#19705.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-14 14:05 UTC, ovh-cds commented
CDS Report build-cds#19707.1 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-14 14:36 UTC, ovh-cds commented
CDS Report build-cds#19708.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-14 15:02 UTC, ovh-cds commented
CDS Report integration-cds#19708.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-15 10:16 UTC, sguiheux requested changes

2023-12-15 10:16 UTC, sguiheux commented on sdk/v2_workflow_run.go
> -	Integrations  *V2WorkflowRunJobIntegrations `json:"integrations,omitempty" db:"integrations"`
Need sql to remove the column

2023-12-15 12:38 UTC, fsamin commented on sdk/v2_workflow_run.go
> -	Integrations  *V2WorkflowRunJobIntegrations `json:"integrations,omitempty" db:"integrations"`
done

2023-12-15 12:54 UTC, ovh-cds commented
CDS Report build-cds#19710.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-15 12:58 UTC, sguiheux approved these changes

2023-12-15 13:18 UTC, ovh-cds commented
CDS Report integration-cds#19710.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-02 10:00 UTC, ovh-cds commented
CDS Report build-cds#19794.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-02 10:23 UTC, ovh-cds commented
CDS Report integration-cds#19794.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-01-02 11:17 UTC, ovh-cds commented
CDS Report build-cds#19800.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-02 11:36 UTC, ovh-cds commented
CDS Report integration-cds#19800.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-01-02 13:20 UTC, ovh-cds commented
CDS Report integration-cds#19800.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-02 13:31 UTC, merged