Manual job run
ovh/cds pull request #6734
Opened 2023-12-15 15:47 UTC by sguiheux

[ ] Generate gate jsonschema (enum)
[ ] Display gate event on workflow run UI
[ ] IT
[ ] Cli: trigger job

2023-12-15 15:54 UTC, ovh-cds commented
CDS Report build-cds#19711.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-15 16:18 UTC, ovh-cds commented
CDS Report integration-cds#19711.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-15 17:17 UTC, ovh-cds commented
CDS Report build-cds#19713.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-15 17:38 UTC, ovh-cds commented
CDS Report integration-cds#19713.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✘

2023-12-18 08:15 UTC, ovh-cds commented
CDS Report build-cds#19714.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 08:35 UTC, ovh-cds commented
CDS Report integration-cds#19714.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-12-18 09:02 UTC, ovh-cds commented
CDS Report build-cds#19716.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 09:26 UTC, ovh-cds commented
CDS Report integration-cds#19716.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-12-18 10:30 UTC, ovh-cds commented
CDS Report build-cds#19717.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 10:50 UTC, ovh-cds commented
CDS Report integration-cds#19717.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2023-12-18 12:56 UTC, ovh-cds commented
CDS Report build-cds#19718.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 13:32 UTC, ovh-cds commented
CDS Report build-cds#19719.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 14:06 UTC, ovh-cds commented
CDS Report build-cds#19720.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-18 14:31 UTC, ovh-cds commented
CDS Report integration-cds#19720.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-18 16:57 UTC, richardlt approved these changes

2023-12-27 08:01 UTC, ovh-cds commented
CDS Report build-cds#19767.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-27 08:24 UTC, ovh-cds commented
CDS Report integration-cds#19767.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2023-12-27 08:50 UTC, ovh-cds commented
CDS Report integration-cds#19767.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-02 09:54 UTC, yesnault approved these changes

2024-01-02 09:59 UTC, fsamin requested changes

2024-01-02 09:59 UTC, fsamin commented on engine/api/v2_workflow_run.go
> +				return sdk.NewErrorFrom(sdk.ErrForbidden, "gate condition are not satisfied")
```suggestion
				return sdk.NewErrorFrom(sdk.ErrForbidden, "gate conditions are not satisfied")
```

2024-01-02 10:15 UTC, ovh-cds commented
CDS Report build-cds#19797.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-02 10:37 UTC, ovh-cds commented
CDS Report integration-cds#19797.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-01-03 09:50 UTC, ovh-cds commented
CDS Report integration-cds#19797.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-03 11:09 UTC, ovh-cds commented
CDS Report build-cds#19807.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 11:31 UTC, ovh-cds commented
CDS Report integration-cds#19807.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-03 13:14 UTC, fsamin approved these changes

2024-01-03 13:25 UTC, merged