feat(api): add vcs/repo/run events
ovh/cds pull request #6752
Opened 2023-12-26 14:41 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2023-12-26 14:55 UTC, ovh-cds commented
CDS Report build-cds#19764.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-26 15:13 UTC, ovh-cds commented
CDS Report build-cds#19765.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-26 15:37 UTC, ovh-cds commented
CDS Report integration-cds#19765.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-26 16:48 UTC, ovh-cds commented
CDS Report build-cds#19766.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-26 17:10 UTC, ovh-cds commented
CDS Report integration-cds#19766.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2023-12-27 07:54 UTC, ovh-cds commented
CDS Report integration-cds#19766.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-27 09:44 UTC, ovh-cds commented
CDS Report build-cds#19769.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-27 10:16 UTC, ovh-cds commented
CDS Report integration-cds#19769.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2023-12-27 10:32 UTC, ovh-cds commented
CDS Report integration-cds#19769.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2023-12-27 10:53 UTC, ovh-cds commented
CDS Report integration-cds#19769.3 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-27 16:12 UTC, ovh-cds commented
CDS Report build-cds#19783.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2023-12-27 16:51 UTC, ovh-cds commented
CDS Report build-cds#19783.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2023-12-27 17:14 UTC, ovh-cds commented
CDS Report integration-cds#19783.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2023-12-29 16:05 UTC, richardlt approved these changes

2024-01-02 09:07 UTC, yesnault approved these changes

2024-01-02 10:19 UTC, fsamin commented on engine/api/event_v2/event_permission.go
> +	previousBts, _ := json.Marshal(previousPerm)
Are we sure we need the previous struct ?
In my ming we have it in the previous event

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_permission.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_permission.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_organization.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_hatchery.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_hatchery.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:20 UTC, fsamin commented on engine/api/event_v2/event_hatchery.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:21 UTC, fsamin commented on engine/api/event_v2/event_entity.go
> +	if u != nil {
if the user can be nil if some case, we should never set it.

event data must be reliable

2024-01-02 10:22 UTC, fsamin commented on engine/api/event_v2/event_analysis.go
> +	if u != nil {
if the user can be nil if some case, we should never set it.

event data must be reliable

2024-01-02 10:22 UTC, fsamin commented on engine/api/event_v2/event_plugin.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:23 UTC, fsamin commented on engine/api/event_v2/event_plugin.go
> +	previousBts, _ := json.Marshal(pOld)
do we need the previous one ?

2024-01-02 10:25 UTC, fsamin commented on engine/api/event_v2/event_plugin.go
> +	if u != nil {
is it possible to have a nil user ?

2024-01-02 10:26 UTC, fsamin commented on engine/api/event_v2/event_run.go
> +	e := sdk.EventV2{
in fact i'm not sure it's a good idea to share the same structure for all events...

2024-01-03 10:11 UTC, ovh-cds commented
CDS Report build-cds#19804.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 10:54 UTC, ovh-cds commented
CDS Report build-cds#19805.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 11:17 UTC, ovh-cds commented
CDS Report integration-cds#19805.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-03 13:22 UTC, ovh-cds commented
CDS Report integration-cds#19805.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-03 13:54 UTC, ovh-cds commented
CDS Report build-cds#19811.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 14:16 UTC, ovh-cds commented
CDS Report integration-cds#19811.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-05 09:55 UTC, fsamin requested changes

2024-01-05 09:55 UTC, fsamin commented on engine/api/event_v2/event_analysis.go
> +	if u != nil {
remove this

2024-01-05 09:55 UTC, fsamin commented on engine/api/event_v2/event_entity.go
> +	if u != nil {
```suggestion
  // User is nil for deletion (entity deletion is initiated by CDS itself)
	if u != nil {
```

2024-01-05 09:55 UTC, fsamin commented on engine/api/event_v2/event_hatchery.go
> +	if u != nil {
```suggestion
  // user is nil for update event, because the hatchery updates itself
	if u != nil {
```

2024-01-05 10:42 UTC, fsamin approved these changes

2024-01-05 10:48 UTC, ovh-cds commented
CDS Report build-cds#19824.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-05 11:10 UTC, ovh-cds commented
CDS Report integration-cds#19824.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-05 15:40 UTC, merged