doc: README
ovh/cds pull request #6768
Opened 2024-01-03 09:45 UTC by yesnault

2024-01-03 09:46 UTC, richardlt approved these changes

2024-01-03 09:53 UTC, sguiheux approved these changes

2024-01-03 10:01 UTC, ovh-cds commented
CDS Report build-cds#19802.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-03 10:14 UTC, fsamin requested changes

2024-01-03 10:14 UTC, fsamin commented on README.md
> +CDS provides an intuitive UI that allows you to build complex workflows, run them, and dig into the logs when needed.
```suggestion
CDS provides an intuitive UI that allows you to build complex workflows, run them and dig into the logs when needed.
```

2024-01-03 10:14 UTC, fsamin commented on README.md
> +Pipeline as code is a well-known concept of CI / CD tools. CDS goes a step further and offers workflow as code. This is done by git-pushing using .yaml configuration files of your workflow (+ pipelin
not really because the files are yaml files but must be .yml

2024-01-03 10:14 UTC, fsamin commented on README.md
> +You can modify your workflow with the UI, you can also modify the configuration by editing the .yaml file directly in the UI if you wish. This is an excellent way to learn how to use the workflow-as-
same

2024-01-03 10:14 UTC, fsamin commented on README.md
> +Users are free to create groups and manage users in their groups. A group can have the right to read, write, and execute their projects and their workflows. You can also restrict the execution of som
```suggestion
Users are free to create groups and manage users in their groups. A group can have the right to read, write and execute their projects and their workflows. You can also restrict the execution of some pipelines to some groups if you wish.
```

2024-01-03 10:14 UTC, fsamin commented on README.md
> +A worker model can be a docker image, an OpenStack image, or a VSphere image.
```suggestion
A worker model can be a docker image, an OpenStack image or a VSphere image.
```

2024-01-03 10:14 UTC, fsamin commented on README.md
> +All you can do with the UI is available via the Command-Line Interface (CLI), named "cdsctl". cdsctl is available on all the OS: Darwin, FreeBSD, Linux, OpenBSD... cdsctl will allow you to create, la
```suggestion
All you can do with the UI is available via the Command-Line Interface (CLI), named "cdsctl". cdsctl is available on all the OS: Darwin, FreeBSD, Linux, OpenBSD... cdsctl will allow you to create, launch, export, import your workflows, monitor your CDS and navigate through your projects and workflows.
```

2024-01-03 10:28 UTC, ovh-cds commented
CDS Report integration-cds#19802.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-03 13:32 UTC, yesnault commented on README.md
> +Pipeline as code is a well-known concept of CI / CD tools. CDS goes a step further and offers workflow as code. This is done by git-pushing using .yaml configuration files of your workflow (+ pipelin
```suggestion
Pipeline as code is a well-known concept of CI / CD tools. CDS goes a step further and offers workflow as code. This is done by git-pushing using yaml configuration files of your workflow (+ pipeline, + applications, + environment). This is particularly useful as you can test your new workflow on a dev branch, before merging the changes on the master branch.
```

2024-01-03 13:32 UTC, yesnault commented on README.md
> +You can modify your workflow with the UI, you can also modify the configuration by editing the .yaml file directly in the UI if you wish. This is an excellent way to learn how to use the workflow-as-
```suggestion
You can modify your workflow with the UI, you can also modify the configuration by editing the yaml file directly in the UI if you wish. This is an excellent way to learn how to use the workflow-as-code feature.
```

2024-01-03 13:50 UTC, ovh-cds commented
CDS Report build-cds#19810.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-05 10:18 UTC, ovh-cds commented
CDS Report integration-cds#19810.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-01-05 10:44 UTC, ovh-cds commented
CDS Report integration-cds#19810.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-05 15:59 UTC, merged