feat(api): add project notifications
ovh/cds pull request #6774
Opened 2024-01-05 16:17 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-01-05 16:23 UTC, ovh-cds commented
CDS Report build-cds#19836.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2024-01-05 16:23 UTC, yesnault requested changes

2024-01-05 16:23 UTC, yesnault commented on sdk/event_v2.go
> +	Notification  string          `json:"notification"`
```suggestion
	Notification  string          `json:"notification,omitempty"`
```

2024-01-05 16:42 UTC, ovh-cds commented
CDS Report build-cds#19837.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-05 17:02 UTC, ovh-cds commented
CDS Report integration-cds#19837.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-09 12:54 UTC, fsamin requested changes

2024-01-09 12:54 UTC, fsamin commented on cli/cdsctl/experimental_project_notification.go
> +	Short:   "Import a notification on a project from a yaml file",
```suggestion
	Short:   "Import notification settings on a project from a yaml file",
```

2024-01-09 12:54 UTC, fsamin commented on cli/cdsctl/experimental_project_notification.go
> +	Short:   "Export a notification from a project to stdout",
```suggestion
	Short:   "Export notification settings from a project",
```

2024-01-09 12:54 UTC, fsamin commented on cli/cdsctl/experimental_project_notification.go
> +	Example: "cdsctl notification export MY-PROJECT MY-VCS-SERVER-NAME > file.yaml",
```suggestion
	Example: "cdsctl notification export MY-PROJECT MY-VCS-SERVER-NAME",
```

2024-01-10 09:59 UTC, richardlt approved these changes

2024-01-10 09:59 UTC, yesnault approved these changes

2024-01-10 10:22 UTC, ovh-cds commented
CDS Report build-cds#19858.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-10 10:52 UTC, ovh-cds commented
CDS Report build-cds#19860.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-10 11:16 UTC, ovh-cds commented
CDS Report integration-cds#19860.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-15 14:54 UTC, fsamin approved these changes

2024-01-16 08:47 UTC, merged