feat(api): add project secrets
ovh/cds pull request #6794
Opened 2024-01-17 09:31 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-01-17 09:47 UTC, ovh-cds commented
CDS Report build-cds#19900.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-17 10:24 UTC, ovh-cds commented
CDS Report integration-cds#19900.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-18 16:18 UTC, yesnault requested changes

2024-01-18 16:18 UTC, yesnault commented on cli/cdsctl/experimental_project_secret.go
> +	Aliases: []string{""},
```suggestion
	Aliases: []string{"secrets"},
```

2024-01-18 16:18 UTC, yesnault commented on cli/cdsctl/experimental_project_secret.go
> +	Short:   "Manage secret on a CDS project",
```suggestion
	Short:   "Manage secrets on a CDS project",
```

2024-01-18 16:18 UTC, yesnault commented on cli/cdsctl/experimental_project_secret.go
> +	Short: "List secret available on a project",
```suggestion
	Short: "List secrets available on a project",
```

2024-01-19 14:05 UTC, ovh-cds commented
CDS Report build-cds#19935.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-19 14:30 UTC, ovh-cds commented
CDS Report integration-cds#19935.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-19 15:57 UTC, fsamin requested changes

2024-01-19 15:57 UTC, fsamin commented on engine/api/v2_project_secret.go
> +	return service.RBAC(api.projectManage),
maybe we should a have a permission for secrets

2024-01-19 15:57 UTC, fsamin commented on engine/api/v2_project_secret.go
> +	return service.RBAC(api.projectManage),
same

2024-01-19 15:57 UTC, fsamin commented on engine/api/v2_project_secret.go
> +			reg, err := regexp.Compile(sdk.SecretNamePattern)
use mustCompile and only once

2024-01-19 15:57 UTC, fsamin commented on engine/api/v2_project_secret.go
> +			reg, err := regexp.Compile(sdk.SecretNamePattern)
same

2024-01-19 15:57 UTC, fsamin commented on engine/api/v2_queue_worker.go
> +		secrets := computeSecretsContext(ctx, *projWithSecrets, projectSecrets, *vcsWithSecrets)
Are all the secrets injected for all workflow runs, without any declaration ?

2024-01-23 08:40 UTC, closed without merging