feat(api,cli): add project variable set
ovh/cds pull request #6806
Opened 2024-01-24 13:39 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-01-24 13:47 UTC, ovh-cds commented
CDS Report build-cds#19961.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-24 14:07 UTC, ovh-cds commented
CDS Report integration-cds#19961.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-24 14:32 UTC, ovh-cds commented
CDS Report integration-cds#19961.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-24 14:44 UTC, ovh-cds commented
CDS Report integration-cds#19961.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-24 14:58 UTC, ovh-cds commented
CDS Report build-cds#19963.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2024-01-24 15:14 UTC, ovh-cds commented
CDS Report build-cds#19964.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-01-24 15:34 UTC, ovh-cds commented
CDS Report build-cds#19965.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-24 15:51 UTC, ovh-cds commented
CDS Report integration-cds#19965.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-24 17:06 UTC, ovh-cds commented
CDS Report build-cds#19966.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-24 17:26 UTC, ovh-cds commented
CDS Report integration-cds#19966.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-25 08:02 UTC, ovh-cds commented
CDS Report integration-cds#19966.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-25 09:43 UTC, richardlt approved these changes

2024-01-25 13:11 UTC, yesnault requested changes

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset.go
> +	Short:   "List all variabelset in the given project",
```suggestion
	Short:   "List all variable sets in the given project",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset.go
> +	Short:   "Delete a variableset on a project",
```suggestion
	Short:   "Delete a variable set on a project",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short:   "Manage item on a CDS project variableset",
```suggestion
	Short:   "Manage item on a CDS project Variable Set",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short: "List the items of the given variableset",
```suggestion
	Short: "List the items of the given Variable Set",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short:   "Get the given variableset item",
```suggestion
	Short:   "Get the given variable set item",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +		{Name: "variableset-name"},
```suggestion
		{Name: "variable-set-name"},
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset.go
> +	Short:   "Manage VariableSet on a CDS project",
```suggestion
	Short:   "Manage Variable Set on a CDS project",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short:   "Delete an item from a variableset",
```suggestion
	Short:   "Delete an item from a variable set",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short:   "Create a new item inside a variableset ",
```suggestion
	Short:   "Create a new item inside a variable set",
```

2024-01-25 13:11 UTC, yesnault commented on cli/cdsctl/experimental_project_variableset_item.go
> +	Short:   "Update an item inside a variableset ",
```suggestion
	Short:   "Update an item inside a variable set",
```

2024-01-25 13:13 UTC, yesnault approved these changes

2024-01-25 13:29 UTC, ovh-cds commented
CDS Report build-cds#19967.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-26 08:07 UTC, ovh-cds commented
CDS Report integration-cds#19967.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-26 08:07 UTC, merged