feat(api,ui): run v2 show repo info
ovh/cds pull request #6807
Opened 2024-01-25 14:55 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-01-25 15:04 UTC, sguiheux requested changes

2024-01-25 15:04 UTC, sguiheux commented on engine/api/workflow_v2/dao_run.go
> +			project_key = $1
Index for this kind of request?

2024-01-25 15:23 UTC, sguiheux approved these changes

2024-01-25 15:36 UTC, ovh-cds commented
CDS Report build-cds#19970.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-25 16:00 UTC, ovh-cds commented
CDS Report integration-cds#19970.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-01-26 09:26 UTC, ovh-cds commented
CDS Report build-cds#19974.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-26 09:46 UTC, ovh-cds commented
CDS Report build-cds#19975.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-26 10:10 UTC, ovh-cds commented
CDS Report integration-cds#19975.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-01-26 10:15 UTC, merged