feat(contrib): add arsenal deployment
ovh/cds pull request #6811
Opened 2024-01-26 15:59 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-01-26 16:13 UTC, ovh-cds commented
CDS Report build-cds#19981.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-29 15:14 UTC, ovh-cds commented
CDS Report build-cds#19984.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-01-29 15:42 UTC, ovh-cds commented
CDS Report integration-cds#19984.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-01 13:20 UTC, fsamin requested changes

2024-02-01 13:57 UTC, ovh-cds commented
CDS Report build-cds#20003.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-02-01 14:30 UTC, ovh-cds commented
CDS Report build-cds#20003.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-01 15:22 UTC, ovh-cds commented
CDS Report integration-cds#20003.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-01 15:35 UTC, yesnault approved these changes

2024-02-05 08:48 UTC, richardlt approved these changes

2024-02-05 08:49 UTC, richardlt requested changes

2024-02-05 08:49 UTC, richardlt commented on ui/proxy.conf.json
> +    "target": "http://localhost:9081",
revert
```suggestion
    "target": "http://localhost:8081",
```

2024-02-05 08:50 UTC, richardlt approved these changes

2024-02-05 08:52 UTC, fsamin approved these changes

2024-02-05 09:05 UTC, ovh-cds commented
CDS Report build-cds#20030.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-05 09:34 UTC, ovh-cds commented
CDS Report integration-cds#20030.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-05 09:42 UTC, merged