feat(contrib): docker-push plugin
ovh/cds pull request #6813
Opened 2024-02-01 09:24 UTC by fsamin

2024-02-01 09:39 UTC, ovh-cds commented
CDS Report build-cds#19998.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-01 10:22 UTC, ovh-cds commented
CDS Report integration-cds#19998.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-01 10:47 UTC, ovh-cds commented
CDS Report integration-cds#19998.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-01 15:53 UTC, richardlt approved these changes

2024-02-01 16:06 UTC, yesnault requested changes

2024-02-01 16:22 UTC, ovh-cds commented
CDS Report build-cds#20006.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-01 16:46 UTC, ovh-cds commented
CDS Report integration-cds#20006.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-02 07:53 UTC, sguiheux requested changes

2024-02-02 07:53 UTC, sguiheux commented on contrib/grpcplugins/action/docker-push/docker-push.yml
> +      This parameter can be empty if you want to keep the same tag.
You return an eror when the field is empty

2024-02-02 07:53 UTC, sguiheux commented on contrib/grpcplugins/action/docker-push/main.go
> +	if len(tags) == 0 {
You say that tags can be empty in plugin descriptor file

2024-02-02 07:53 UTC, sguiheux commented on contrib/grpcplugins/action/docker-push/main.go
> +		destination = registry + "/" + img.repository + ":" + tag
Maybe we have to failed if (no registry && no auth) ?

2024-02-02 07:53 UTC, sguiheux commented on contrib/grpcplugins/action/docker-push/main.go
> +	// Upload the file to an artifactory or CDN
We do not upload to CDN

2024-02-02 08:31 UTC, ovh-cds commented
CDS Report build-cds#20009.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-02 08:55 UTC, ovh-cds commented
CDS Report integration-cds#20009.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-02 09:13 UTC, yesnault approved these changes

2024-02-02 09:51 UTC, sguiheux approved these changes

2024-02-02 09:51 UTC, merged