feat(contrib): add deployment run result
ovh/cds pull request #6821
Opened 2024-02-05 14:09 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-02-05 14:29 UTC, ovh-cds commented
CDS Report build-cds#20033.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-05 14:56 UTC, ovh-cds commented
CDS Report integration-cds#20033.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-05 15:44 UTC, fsamin approved these changes

2024-02-05 16:02 UTC, yesnault requested changes

2024-02-05 16:02 UTC, yesnault commented on contrib/integrations/arsenal/arsenal.go
> +	DeploymentFamily string `json:"deploymentFamily"`
deploymentFamily or deployment_family ?

2024-02-05 16:12 UTC, yesnault approved these changes

2024-02-05 16:28 UTC, ovh-cds commented
CDS Report build-cds#20037.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-02-05 16:49 UTC, ovh-cds commented
CDS Report build-cds#20037.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-05 17:18 UTC, ovh-cds commented
CDS Report integration-cds#20037.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-09 08:17 UTC, richardlt approved these changes

2024-02-12 08:12 UTC, merged