feat(hooks): trigger on pull-request
ovh/cds pull request #6825
Opened 2024-02-07 17:52 UTC by yesnault

2024-02-07 18:01 UTC, ovh-cds commented
CDS Report build-cds#20062.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-07 18:31 UTC, ovh-cds commented
CDS Report integration-cds#20062.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-09 14:50 UTC, ovh-cds commented
CDS Report build-cds#20070.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-09 15:21 UTC, ovh-cds commented
CDS Report integration-cds#20070.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-09 16:14 UTC, ovh-cds commented
CDS Report integration-cds#20070.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-09 16:40 UTC, ovh-cds commented
CDS Report integration-cds#20070.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-09 17:26 UTC, ovh-cds commented
CDS Report build-cds#20075.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-09 17:47 UTC, ovh-cds commented
CDS Report integration-cds#20075.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-09 18:23 UTC, ovh-cds commented
CDS Report build-cds#20077.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-09 18:52 UTC, ovh-cds commented
CDS Report integration-cds#20077.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-11 10:20 UTC, ovh-cds commented
CDS Report build-cds#20078.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-11 10:50 UTC, ovh-cds commented
CDS Report build-cds#20079.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-11 11:20 UTC, ovh-cds commented
CDS Report integration-cds#20079.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-11 12:26 UTC, ovh-cds commented
CDS Report build-cds#20080.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-11 12:58 UTC, ovh-cds commented
CDS Report integration-cds#20080.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-11 15:38 UTC, ovh-cds commented
CDS Report build-cds#20081.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-02-11 16:39 UTC, ovh-cds commented
CDS Report build-cds#20081.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-11 17:04 UTC, ovh-cds commented
CDS Report integration-cds#20081.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-02-12 08:11 UTC, ovh-cds commented
CDS Report integration-cds#20081.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-12 08:19 UTC, richardlt approved these changes

2024-02-12 08:24 UTC, sguiheux requested changes

2024-02-12 08:24 UTC, sguiheux commented on engine/hooks/hook_repository_event.go
> +		extractedData.Ref = "refs/heads/" + request.PullRequest.Head.Ref
use sdk.GitRefBranchPrefix

2024-02-12 08:24 UTC, sguiheux commented on sdk/v2_workflow.go
>  	ModelUpdate        *WorkflowOnModelUpdate        `json:"model_update,omitempty"`
model-update

2024-02-12 08:24 UTC, sguiheux commented on sdk/v2_workflow.go
>  	WorkflowUpdate     *WorkflowOnWorkflowUpdate     `json:"workflow_update,omitempty"`
workflow-update

2024-02-12 08:54 UTC, ovh-cds commented
CDS Report build-cds#20084.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-12 09:23 UTC, ovh-cds commented
CDS Report integration-cds#20084.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-12 13:31 UTC, fsamin approved these changes

2024-02-13 07:55 UTC, sguiheux approved these changes

2024-02-13 07:58 UTC, ovh-cds commented
CDS Report build-cds#20093.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-13 08:30 UTC, ovh-cds commented
CDS Report integration-cds#20093.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-13 09:22 UTC, merged