feat(contrib): helm push plugin
ovh/cds pull request #6826
Opened 2024-02-08 16:31 UTC by fsamin

2024-02-08 16:37 UTC, yesnault approved these changes

2024-02-08 16:47 UTC, ovh-cds commented
CDS Report build-cds#20068.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-08 17:14 UTC, ovh-cds commented
CDS Report integration-cds#20068.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-09 08:16 UTC, richardlt approved these changes

2024-02-09 17:13 UTC, ovh-cds commented
CDS Report build-cds#20076.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-09 17:41 UTC, ovh-cds commented
CDS Report integration-cds#20076.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-12 08:36 UTC, sguiheux requested changes

2024-02-12 08:36 UTC, sguiheux commented on contrib/grpcplugins/action/helm-push/helm-push.yml
> +name: docker-push
helm-push

2024-02-13 17:15 UTC, sguiheux approved these changes

2024-02-13 17:44 UTC, ovh-cds commented
CDS Report build-cds#20108.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-13 18:08 UTC, ovh-cds commented
CDS Report integration-cds#20108.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-14 08:00 UTC, merged