wip
ovh/cds pull request #6829
Opened 2024-02-12 08:00 UTC by richardlt

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-02-12 08:06 UTC, yesnault approved these changes

2024-02-12 08:47 UTC, sguiheux requested changes

2024-02-12 08:47 UTC, sguiheux commented on engine/api/v2_workflow_run_job_routines.go
> +	jobSchedulingTimeout = 60.0
use configuration value

2024-02-12 09:27 UTC, ovh-cds commented
CDS Report build-cds#20086.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-12 09:54 UTC, ovh-cds commented
CDS Report integration-cds#20086.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-13 09:23 UTC, sguiheux approved these changes

2024-02-13 09:23 UTC, merged