feat(api): add run result of type coverage
ovh/cds pull request #6849
Opened 2024-02-20 13:51 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-02-20 14:05 UTC, ovh-cds commented
CDS Report build-cds#20159.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-20 14:44 UTC, ovh-cds commented
CDS Report integration-cds#20159.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-21 08:16 UTC, fsamin requested changes

2024-02-21 08:16 UTC, fsamin commented on engine/worker/pkg/workerruntime/types.go
> +	Type                 []string
```suggestion
	Type                 []sdk.V2WorkflowRunResultType
```

2024-02-21 09:53 UTC, ovh-cds commented
CDS Report integration-cds#20163.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-21 16:41 UTC, yesnault approved these changes

2024-02-22 14:03 UTC, fsamin approved these changes

2024-02-22 14:03 UTC, merged