feat(workflowv2/plugin): artifactory release
ovh/cds pull request #6853
Opened 2024-02-21 13:21 UTC by fsamin

2024-02-21 13:36 UTC, ovh-cds commented
CDS Report build-cds#20165.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-21 15:46 UTC, richardlt approved these changes

2024-02-21 15:56 UTC, sguiheux requested changes

2024-02-21 15:56 UTC, sguiheux commented on contrib/grpcplugins/action/artifactory-release/main.go
> +		res.Status = err.Error()
```suggestion
		res.Details = err.Error()
```

2024-02-21 16:40 UTC, yesnault requested changes

2024-02-21 16:40 UTC, yesnault commented on contrib/grpcplugins/action/artifactory-release/artifactory-release.yml
> +    description: Artifact name or wilcard pattern.
```suggestion
    description: Artifact name or wildcard pattern.
```

2024-02-21 17:45 UTC, ovh-cds commented
CDS Report build-cds#20168.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-21 18:12 UTC, ovh-cds commented
CDS Report integration-cds#20168.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-22 10:36 UTC, ovh-cds commented
CDS Report integration-cds#20171.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-22 14:00 UTC, yesnault approved these changes

2024-02-22 14:01 UTC, merged