feat(contrib,sdk): add junit plugin
ovh/cds pull request #6859
Opened 2024-02-22 14:47 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-02-22 15:47 UTC, ovh-cds commented
CDS Report integration-cds#20183.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-23 08:14 UTC, fsamin requested changes

2024-02-23 08:14 UTC, fsamin commented on contrib/grpcplugins/action/junit/main.go
> +
don't copy paste the uploadArtifact code

2024-02-23 09:44 UTC, ovh-cds commented
CDS Report build-cds#20190.0 ✘  
* Build
  * Build and Package All ✘  
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-23 10:25 UTC, ovh-cds commented
CDS Report build-cds#20192.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-23 10:50 UTC, ovh-cds commented
CDS Report integration-cds#20192.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-23 13:05 UTC, ovh-cds commented
CDS Report integration-cds#20192.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-23 13:41 UTC, ovh-cds commented
CDS Report integration-cds#20192.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-26 09:14 UTC, ovh-cds commented
CDS Report build-cds#20201.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-26 09:39 UTC, ovh-cds commented
CDS Report integration-cds#20201.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-02-26 10:07 UTC, ovh-cds commented
CDS Report integration-cds#20201.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-26 11:19 UTC, ovh-cds commented
CDS Report build-cds#20203.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-26 11:49 UTC, ovh-cds commented
CDS Report integration-cds#20203.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-26 13:43 UTC, fsamin approved these changes

2024-02-26 13:50 UTC, richardlt approved these changes

2024-02-26 14:17 UTC, merged