fix(jsonschema): fix job validation
ovh/cds pull request #6874
Opened 2024-02-28 10:02 UTC by rclsilver

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-02-28 10:45 UTC, ovh-cds commented
CDS Report build-cds#20216.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-02-28 11:54 UTC, ovh-cds commented
CDS Report build-cds#20216.1 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-28 12:24 UTC, ovh-cds commented
CDS Report integration-cds#20216.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-02-28 13:05 UTC, yesnault approved these changes

2024-02-28 16:44 UTC, fsamin approved these changes

2024-02-29 14:12 UTC, richardlt requested changes
Allow short ref usage

2024-02-29 14:12 UTC, richardlt commented on engine/api/v2_jsonschema.go
> +		wmNames = append(wmNames, fmt.Sprintf("%s/%s/%s/%s@%s", wm.ProjectKey, wm.VCSName, wm.RepoName, wm.Name, wm.Ref))
```suggestion
		wmNames = append(wmNames, fmt.Sprintf("%s/%s/%s/%s@%s", wm.ProjectKey, wm.VCSName, wm.RepoName, wm.Name, wm.Ref))
		shortRef := strings.TrimPrefix(strings.TrimPrefix(wm.Ref, sdk.GitRefBranchPrefix), sdk.GitRefTagPrefix)
		wmNames = append(wmNames, fmt.Sprintf("%s/%s/%s/%s@%s", wm.ProjectKey, wm.VCSName, wm.RepoName, wm.Name, shortRef))
```

2024-02-29 14:57 UTC, ovh-cds commented
CDS Report build-cds#20221.0 ✔ 
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-02-29 15:25 UTC, ovh-cds commented
CDS Report integration-cds#20221.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-03-01 09:25 UTC, richardlt approved these changes

2024-03-01 09:43 UTC, ovh-cds commented
CDS Report integration-cds#20221.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-03-01 09:47 UTC, merged