feat(contrib): add debian push plugin
ovh/cds pull request #6888
Opened 2024-03-07 09:38 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-03-07 09:49 UTC, richardlt approved these changes

2024-03-07 10:02 UTC, ovh-cds commented
CDS Report build-cds#20248.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-03-11 15:34 UTC, richardlt approved these changes

2024-03-11 15:35 UTC, ovh-cds commented
CDS Report build-cds#20270.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-03-11 16:02 UTC, ovh-cds commented
CDS Report integration-cds#20270.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-03-11 16:25 UTC, yesnault requested changes

2024-03-11 16:25 UTC, yesnault commented on contrib/grpcplugins/action/debianPush/debianPush.yml
> +description: This push Debian package on an artifactory debian repository.
```suggestion
description: This pushes Debian package on an artifactory debian repository. 
```

2024-03-13 07:45 UTC, yesnault approved these changes

2024-03-13 07:45 UTC, merged