feat(api): add search all workflows api + add docker layer in buildinfo
ovh/cds pull request #6922
Opened 2024-04-02 09:28 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-04-02 09:41 UTC, ovh-cds commented
CDS Report integration-cds#20444.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-04-03 05:15 UTC, yesnault requested changes

2024-04-03 05:15 UTC, yesnault commented on engine/sql/api/295_v2_run_git_context.sql
> +-- +migrate Up
It's 296 now

2024-04-03 15:09 UTC, yesnault approved these changes

2024-04-03 15:25 UTC, ovh-cds commented
CDS Report build-cds#20447.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-04-03 15:53 UTC, ovh-cds commented
CDS Report integration-cds#20447.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-04-03 16:04 UTC, merged