fix(api,cdn): new signatures
ovh/cds pull request #6966
Opened 2024-05-22 09:48 UTC by fsamin

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-05-22 10:03 UTC, ovh-cds commented
CDS Report build-cds#20604.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-05-22 10:45 UTC, ovh-cds commented
CDS Report integration-cds#20604.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-05-22 14:43 UTC, yesnault approved these changes

2024-05-23 08:55 UTC, sguiheux approved these changes

2024-05-23 08:59 UTC, richardlt requested changes

2024-05-23 08:59 UTC, richardlt commented on engine/api/integration/gorp_model.go
> +		"{{.IntegrationModelID}}{{.ProjectID}}",
```suggestion
```

2024-05-23 08:59 UTC, richardlt commented on engine/gorpmapper/table_mapping.go
> +					if is {
!is ?

2024-05-24 13:14 UTC, ovh-cds commented
CDS Report build-cds#20613.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-05-24 13:35 UTC, ovh-cds commented
CDS Report build-cds#20613.1 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-05-24 13:54 UTC, ovh-cds commented
CDS Report integration-cds#20613.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-05-24 14:44 UTC, ovh-cds commented
CDS Report integration-cds#20613.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-05-27 12:18 UTC, merged