feat(api,hooks): add scheduler on workflow v2
ovh/cds pull request #7004
Opened 2024-06-18 07:01 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-06-18 07:19 UTC, yesnault requested changes

2024-06-18 07:19 UTC, yesnault commented on engine/hooks/scheduler_v2.go
> +			schedulerExecutions, err := s.Dao.GetAllSchedulerExecutions(ctx)
need maintenance aware

2024-06-18 07:48 UTC, ovh-cds commented
CDS Report build-cds#20726.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-06-18 08:23 UTC, ovh-cds commented
CDS Report integration-cds#20726.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-06-18 10:00 UTC, ovh-cds commented
CDS Report integration-cds#20726.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-06-19 06:58 UTC, sguiheux commented on engine/hooks/scheduler_v2.go
> +			schedulerExecutions, err := s.Dao.GetAllSchedulerExecutions(ctx)
fixed

2024-06-19 14:01 UTC, yesnault approved these changes

2024-06-24 09:27 UTC, richardlt requested changes

2024-06-24 09:27 UTC, richardlt commented on engine/api/repositoriesmanager/repositories_manager.go
> +		path += fmt.Sprintf("&noCache=%v", filters.NoCache)
```suggestion
		path += fmt.Sprintf("&noCache=%t", filters.NoCache)
```

2024-06-24 09:27 UTC, richardlt commented on engine/api/repositoriesmanager/repositories_manager.go
> +		path += fmt.Sprintf("&noCache=%v", filters.NoCache)
```suggestion
		path += fmt.Sprintf("&noCache=%t", filters.NoCache)
```

2024-06-24 09:27 UTC, richardlt commented on engine/api/v2_project_clean_ascode.go
> +		return sdk.NewErrorFrom(sdk.ErrUnknownError, "unable to find 1 hook service")
```suggestion
		return sdk.NewErrorFrom(sdk.ErrUnknownError, "unable to find hook service")
```

2024-06-24 09:27 UTC, richardlt commented on engine/api/v2_repository_analyze.go
> +			return api.stopAnalysis(ctx, analysis, sdk.NewErrorFrom(sdk.ErrUnknownError, "unable to instantiate scheduler on hook service"))
Log src error

2024-06-25 07:25 UTC, sguiheux commented on engine/api/v2_repository_analyze.go
> +			return api.stopAnalysis(ctx, analysis, sdk.NewErrorFrom(sdk.ErrUnknownError, "unable to instantiate scheduler on hook service"))
fixed

2024-06-25 07:49 UTC, ovh-cds commented
CDS Report build-cds#20761.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-06-25 08:26 UTC, ovh-cds commented
CDS Report integration-cds#20761.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-06-26 07:33 UTC, fsamin approved these changes

2024-06-26 09:29 UTC, richardlt approved these changes

2024-06-26 09:29 UTC, merged