feat: install sskkey on worker during checkout
ovh/cds pull request #7014
Opened 2024-06-25 07:14 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-06-25 07:26 UTC, ovh-cds commented
CDS Report build-cds#20757.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✘  
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✘  
  * Test UI ✔

2024-06-25 08:23 UTC, ovh-cds commented
CDS Report integration-cds#20763.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-06-26 08:03 UTC, yesnault approved these changes

2024-06-26 08:10 UTC, fsamin requested changes

2024-06-26 08:10 UTC, fsamin commented on contrib/grpcplugins/action/checkout/main.go
> +		if err := grpcplugins.InstallSSHKey(ctx, &p.Common, workDirs, sshKey, "", key.Private); err != nil {
We should install the key where ssh will read it by default:

$HOME/.ssh/id_rsa with 0600

and we have to do `ssh-keyscan -t rsa -p <port> <host> >> $HOME/.ssh/known_hosts`

But $HOME is corrupted by CDS worker, ssh doesn't care about the overrided $HOME. It takes $HOME from /etc/password.


In a CDS v1 script, this works:

```
#!/bin/bash
homedir=$(cat /etc/passwd | grep $(whoami) | cut -d ':' -f 6)
worker key install  proj-robot-cds-fsamin-ssh --file $homedir/.ssh/id_rsa
ssh-keyscan -t rsa -p 7999 git.host.local >> $homedir/.ssh/known_hosts
git clone ssh://git@git.host.local:7999/foo/bar.git
```

Once we install the key in the real $HOME, it's easier.

2024-06-28 12:32 UTC, ovh-cds commented
CDS Report build-cds#20798.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-06-28 12:52 UTC, ovh-cds commented
CDS Report integration-cds#20798.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✘

2024-06-28 15:15 UTC, ovh-cds commented
CDS Report integration-cds#20798.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 07:36 UTC, ovh-cds commented
CDS Report build-cds#20803.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 07:57 UTC, ovh-cds commented
CDS Report integration-cds#20803.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 08:25 UTC, ovh-cds commented
CDS Report build-cds#20804.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 08:46 UTC, ovh-cds commented
CDS Report integration-cds#20804.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 09:06 UTC, ovh-cds commented
CDS Report build-cds#20805.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 09:27 UTC, ovh-cds commented
CDS Report integration-cds#20805.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✘

2024-07-01 09:58 UTC, ovh-cds commented
CDS Report build-cds#20806.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 10:20 UTC, ovh-cds commented
CDS Report integration-cds#20806.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✘

2024-07-01 12:21 UTC, ovh-cds commented
CDS Report integration-cds#20806.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 12:40 UTC, ovh-cds commented
CDS Report build-cds#20807.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 13:07 UTC, ovh-cds commented
CDS Report integration-cds#20807.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 14:01 UTC, ovh-cds commented
CDS Report build-cds#20808.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-01 14:29 UTC, ovh-cds commented
CDS Report integration-cds#20808.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-01 15:50 UTC, ovh-cds commented
CDS Report integration-cds#20808.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-02 07:21 UTC, ovh-cds commented
CDS Report build-cds#20812.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-02 08:00 UTC, ovh-cds commented
CDS Report integration-cds#20812.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-07-02 08:17 UTC, ovh-cds commented
CDS Report integration-cds#20812.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-07-02 09:39 UTC, ovh-cds commented
CDS Report integration-cds#20812.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-07-02 09:49 UTC, fsamin approved these changes

2024-07-03 09:50 UTC, richardlt approved these changes

2024-07-03 09:50 UTC, merged