feat(hooks,cli): add scheduler admin route + cli
ovh/cds pull request #7030
Opened 2024-07-04 10:11 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-07-05 09:55 UTC, fsamin requested changes

2024-07-05 09:55 UTC, fsamin commented on cli/cdsctl/admin_hooks_scheduler.go
> +	Short:   "Delete a specific scheduler by his identifier",
```suggestion
	Short:   "Delete a scheduler by its identifier",
```

2024-07-05 09:55 UTC, fsamin commented on cli/cdsctl/admin_hooks_scheduler.go
> +	Short:   "Get a scheduler by his identifier",
```suggestion
	Short:   "Get a scheduler by its identifier",
```

2024-07-08 06:35 UTC, yesnault requested changes

2024-07-08 06:35 UTC, yesnault commented on cli/cdsctl/admin_hooks_scheduler.go
> +	Aliases: []string{"s", "schedule", "scheudlers"},
```suggestion
	Aliases: []string{"s", "schedule", "schedulers"},
```

2024-07-08 06:35 UTC, yesnault commented on cli/cdsctl/admin_hooks_scheduler.go
> +	Short:   "Manage repositories where there were events",
```suggestion
	Short:   "Manage workflow schedulers",
```

2024-07-08 06:36 UTC, yesnault approved these changes

2024-07-08 07:15 UTC, ovh-cds commented
CDS Report build-cds#20852.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-08 07:32 UTC, ovh-cds commented
CDS Report integration-cds#20852.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-07-09 08:40 UTC, richardlt approved these changes

2024-07-09 08:51 UTC, ovh-cds commented
CDS Report build-cds#20871.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-09 09:07 UTC, ovh-cds commented
CDS Report integration-cds#20871.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-07-10 13:25 UTC, fsamin approved these changes

2024-07-10 13:26 UTC, merged