feat(hooks,api): send insight report
ovh/cds pull request #7047
Opened 2024-07-12 12:26 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-07-12 12:51 UTC, ovh-cds commented
CDS Report build-cds#20926.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-07-12 13:22 UTC, ovh-cds commented
CDS Report build-cds#20928.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-07-12 13:46 UTC, ovh-cds commented
CDS Report build-cds#20928.1 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-07-12 15:07 UTC, ovh-cds commented
CDS Report build-cds#20928.2 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-12 15:11 UTC, fsamin requested changes

2024-07-12 15:11 UTC, fsamin commented on sdk/hooks_repository_event.go
> +		Title:  "OVH CDS Event",
```suggestion
		Title:  "CDS",
```

2024-07-12 15:11 UTC, fsamin commented on sdk/hooks_repository_event.go
> +		Detail: fmt.Sprintf("Event %s with ID %s: %s", h.EventName, h.UUID, h.Status),
```suggestion
		Detail: fmt.Sprintf("Event %q (%s): %s", h.EventName, h.UUID, h.Status),
```

2024-07-12 15:23 UTC, ovh-cds commented
CDS Report integration-cds#20928.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-07-15 07:26 UTC, ovh-cds commented
CDS Report build-cds#20938.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-07-15 07:43 UTC, ovh-cds commented
CDS Report integration-cds#20938.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-07-15 13:41 UTC, ovh-cds commented
CDS Report integration-cds#20938.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-07-16 08:07 UTC, richardlt approved these changes

2024-07-16 09:17 UTC, yesnault approved these changes

2024-07-16 09:41 UTC, fsamin approved these changes

2024-07-16 12:54 UTC, merged