Feat api workflow v2 metrics
ovh/cds pull request #7115
Opened 2024-09-16 13:31 UTC by fsamin

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-09-16 13:42 UTC, ovh-cds commented
CDS Report integration-cds#21243.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-16 14:39 UTC, sguiheux requested changes

2024-09-16 14:39 UTC, sguiheux commented on engine/api/status.go
> +				api.countMetric(ctx, api.Metrics.nbWorkflowsAsCodeV2, "select count(distinct entity.project_key || '/' || vcs_project.name || '/' || project_repository.name  || '/' || entity.name)  from entity j
```suggestion
				api.countMetric(ctx, api.Metrics.nbWorkflowsAsCodeV2, "select count(distinct(project_repository_id,name)) from entity where type = 'Workflow'")
```

2024-09-16 14:47 UTC, sguiheux approved these changes

2024-09-16 15:06 UTC, ovh-cds commented
CDS Report build-cds#21250.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-09-16 15:45 UTC, ovh-cds commented
CDS Report build-cds#21250.1 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-09-16 16:02 UTC, ovh-cds commented
CDS Report integration-cds#21250.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-09-17 09:18 UTC, yesnault approved these changes

2024-09-17 14:55 UTC, merged