fix(contrib): create directory to checkout if needed
ovh/cds pull request #7121
Opened 2024-09-17 13:51 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-09-17 14:09 UTC, ovh-cds commented
CDS Report build-cds#21263.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-09-17 14:54 UTC, fsamin requested changes

2024-09-17 14:54 UTC, fsamin commented on contrib/grpcplugins/action/checkout/main.go
> +		if err := os.MkdirAll(path, os.ModePerm); err != nil {
ModePerm = [fs](https://pkg.go.dev/io/fs).[ModePerm](https://pkg.go.dev/io/fs#ModePerm) // Unix permission bits, 0o777

not sure it is the right FileMode

2024-09-17 16:21 UTC, richardlt approved these changes

2024-09-17 16:21 UTC, fsamin approved these changes

2024-09-17 17:01 UTC, ovh-cds commented
CDS Report integration-cds#21266.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-18 06:34 UTC, yesnault approved these changes

2024-09-18 06:57 UTC, ovh-cds commented
CDS Report integration-cds#21266.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-18 07:19 UTC, ovh-cds commented
CDS Report build-cds#21272.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-09-18 07:38 UTC, ovh-cds commented
CDS Report integration-cds#21272.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-18 08:01 UTC, ovh-cds commented
CDS Report integration-cds#21272.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-18 08:27 UTC, ovh-cds commented
CDS Report integration-cds#21272.2 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-09-18 08:40 UTC, merged