feat(contrib): retry on HTTP 405 error from Arsenal
ovh/cds pull request #7152
Opened 2024-09-27 14:36 UTC by fsamin

2024-09-27 14:55 UTC, ovh-cds commented
CDS Report build-cds#21376.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-09-27 15:18 UTC, ovh-cds commented
CDS Report integration-cds#21376.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2024-09-27 16:40 UTC, ovh-cds commented
CDS Report integration-cds#21376.2 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-09-30 07:04 UTC, sguiheux requested changes
Maybe update also the action deployArsenal

2024-09-30 07:04 UTC, sguiheux commented on contrib/integrations/arsenal/arsenal.go
> +			time.Sleep(100 * time.Second)
Why 100s ?

2024-09-30 07:34 UTC, ovh-cds commented
CDS Report build-cds#21382.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-09-30 07:50 UTC, ovh-cds commented
CDS Report integration-cds#21382.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2024-09-30 09:59 UTC, sguiheux approved these changes

2024-09-30 10:00 UTC, merged