fix(contrib): check is runresult is part of a release
ovh/cds pull request #7170
Opened 2024-10-11 13:34 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-10-11 13:41 UTC, yesnault approved these changes

2024-10-11 13:56 UTC, ovh-cds commented
CDS Report build-cds#21420.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✘  
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-10-11 14:31 UTC, ovh-cds commented
CDS Report build-cds#21421.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2024-10-11 14:37 UTC, fsamin requested changes

2024-10-11 14:37 UTC, fsamin commented on contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
> +					return promotedArtifact, errors.Errorf("run result %s has already been release in version %s", promotedArtifact, releaseVersion[0])
```suggestion
					return promotedArtifact, errors.Errorf("Run result %s has already been release in version %s", promotedArtifact, releaseVersion[0])
```

2024-10-11 14:37 UTC, fsamin commented on contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
> +					return promotedArtifact, errors.Errorf("run result %s has already been release in version %s", promotedArtifact, releaseVersion[0])
We should write error with grpcplugins.Errorf to have a red message in the job output

2024-10-11 14:51 UTC, ovh-cds commented
CDS Report build-cds#21421.1 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-10-11 15:07 UTC, fsamin approved these changes

2024-10-11 15:23 UTC, ovh-cds commented
CDS Report build-cds#21423.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2024-10-11 15:42 UTC, ovh-cds commented
CDS Report integration-cds#21423.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2024-10-14 07:16 UTC, richardlt approved these changes

2024-10-14 07:17 UTC, merged