feat: project v2 handler
ovh/cds pull request #7256
Opened 2024-12-17 16:10 UTC by sguiheux

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

2024-12-26 10:26 UTC, yesnault requested changes

2024-12-26 10:26 UTC, yesnault commented on engine/api/v2_project.go
> +			// TODO Delete
No need on v2 routes.

2024-12-26 10:26 UTC, yesnault commented on engine/api/v2_project.go
> +			// TODO REMOVE
TODO

2025-01-02 08:07 UTC, sguiheux commented on engine/api/v2_project.go
> +			// TODO Delete
That why there is a TODO. I don't know yet how it will be implement on UI side

2025-01-02 08:07 UTC, sguiheux commented on engine/api/v2_project.go
> +			// TODO REMOVE
same

2025-01-02 09:05 UTC, yesnault approved these changes

2025-01-06 17:06 UTC, ovh-cds commented
CDS Report integration-cds#21674.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✘

2025-01-14 11:04 UTC, ovh-cds commented
CDS Report build-cds#21704.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2025-01-14 11:28 UTC, ovh-cds commented
CDS Report integration-cds#21704.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2025-01-14 13:07 UTC, ovh-cds commented
CDS Report integration-cds#21704.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2025-01-15 13:13 UTC, ovh-cds commented
CDS Report build-cds#21720.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✘  
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✘

2025-01-15 17:24 UTC, ovh-cds commented
CDS Report build-cds#21724.0 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2025-01-15 18:00 UTC, ovh-cds commented
CDS Report build-cds#21724.1 ✘  
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✘  
  * Test SDK ✔ 
  * Test UI ✔

2025-01-16 09:33 UTC, ovh-cds commented
CDS Report build-cds#21727.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2025-01-16 10:30 UTC, ovh-cds commented
CDS Report integration-cds#21727.1 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2025-01-16 16:06 UTC, ovh-cds commented
CDS Report build-cds#21737.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2025-01-16 16:30 UTC, ovh-cds commented
CDS Report integration-cds#21737.0 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone Tests v1 ✘  
  * Standalone Tests v2 ✔

2025-01-17 09:12 UTC, ovh-cds commented
CDS Report integration-cds#21737.1 ✘  
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✘  
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2025-01-17 16:16 UTC, ovh-cds commented
CDS Report build-cds#21746.0 ✔ 
* 
  * Build and Package All -   
  * Build and Package Contrib Action ✔ 
  * Build and Package Contrib Code Plugin ✔ 
  * Build and Package Contrib Integrations ✔ 
  * Build and Package Engine, Worker, CLI and Doc ✔ 
  * Build and Package UI ✔ 
  * Build Debpacker ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Contrib ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test UI ✔

2025-01-17 16:41 UTC, ovh-cds commented
CDS Report integration-cds#21746.0 ✔ 
* Integration
  * Docker Compose Tests ✔ 
  * Standalone Tests ✔ 
  * Standalone Tests v1 ✔ 
  * Standalone Tests v2 ✔

2025-01-20 09:07 UTC, richardlt approved these changes

2025-01-20 09:08 UTC, merged